- .circleci/config.yml
Snyk now supports testing Go code using Go modules, so adding checks of
the dependencies for known vulnerabilities. Also testing the Docker
image builds.
> Adding security checks to the build

- .circleci/config.yml
- .dockerignore
- .gitignore
This would make them more reusable by others, and more explicit.
> Move Snyk instructions into commands

- README.md
> chore: Update readme with slack channel

- Dockerfile
- Makefile
Creates a new target for running our `go` test suite inside the container.
> adds a new make target for running tests

- README.md
- pkg/commands/test/output.go
Exposes the `json` output formatter to the CLI and adds docs.
> exposes json output to cli

- README.md
- pkg/commands/test/output.go
- pkg/commands/test/output_test.go
TAP is a simple but machine readable format for integrating test output
into other toolinig.
> Add TAP output support

- README.md
- examples/awssam/lambda.yaml
- examples/awssam/policy/policy.rego
Hi,
I've created nice example related to [AWSSAM](https://aws.amazon.com/serverless/sam/) framework.
It focus mainly on security issues like overly permissive permissions and sensitive data.
> Example - awssam template

- Dockerfile
- Makefile
The `Dockerfile` didn't seem to be building correctly, so this should resolve that. 
Also added some module caching to speed up the builds a bit.
> Dockerfile fix

- README.md
This is mostly to remove the final line in the `README` as it no longer applies. 
While removing it, also performed some cleanup of the document as a whole.
> Remove auth/oras from notes

- commands/parse/parse.go
> parser: add line break after parsing multi inputs

- commands/commands.go
- commands/test/test.go
Moving --trace and --namespace to the test command as per issue #112
> Move --trace and --namespace to the test command

- internal/commands/test.go
- internal/commands/verify.go
This PR solves #167 and improves #163.
Instead of printing the result of the traces directly on stdout, we now handle it and store it back with the results, so it can be outputted in conftest's format by output.go.
Whilst moving the output of the `test ... --trace` to the output.go as opposed to simply printing it out, I learned that rego.go has a `PrettyTrace` function, which I have used on the verify command and made the type `CheckResult` consistent (now traces is also an `error`.
@jpreese, @boranx, let me know if you're happy with it or want me to change anything.
> Moved output of conftest test `--trace` to output

- README.md
- acceptance.bats
- examples/xml/policy/deny.rego
- examples/xml/pom.xml
- go.mod
- go.sum
- parser/parser.go
- parser/xml/xml.go
- parser/xml/xml_test.go
Fixes: #174 
**Steps:**
- Initially, I started with generic `pom.xml` that used for Java projects.
- Used [generic converter](https://github.com/basgys/goxml2json)
- Added `policy` that tests some maven plugin versions for given `pom.xml`
- Added acceptance test
- Updated `Readme`
<details>
<summary>Example struct (how it is converted)</summary>
```console
$ conftest parse examples/xml/pom.xml
examples/xml/pom.xml
{
"project": {
"-schemaLocation": "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd",
"-xmlns": "http://maven.apache.org/POM/4.0.0",
"-xsi": "http://www.w3.org/2001/XMLSchema-instance",
"artifactId": "simple-example",
"build": {
"plugins": {
"plugin": [
{
"artifactId": "maven-compiler-plugin",
"configuration": {
"encoding": "UTF-8",
"source": "1.8", …
```
> Add XML Support to conftest

- README.md
- examples/ts/policy/deny.rego
* Added example for missing ones
* Order alphabetically
* (NITS): Remove blank line in `examples/ts/policy/deny.rego`
* Better doc
> Update example in README

- internal/commands/verify.go
> Set modules for test compiler

- downloader/detect_oci.go
- downloader/downloader.go
- downloader/get_oci.go
- go.mod
- internal/commands/output.go
- internal/commands/output_test.go
- internal/commands/plugin.go
- internal/commands/plugin_install.go
- internal/commands/test.go
- parser/config.go
- parser/cue/cue.go
- parser/docker/docker.go
- parser/edn/edn.go
- parser/hcl2/hcl2.go
- parser/hocon/hocon.go
- parser/ini/ini.go
- parser/parser_test.go
- parser/terraform/terraform.go
- parser/toml/toml.go
- parser/vcl/vcl.go
- parser/xml/xml.go
- parser/yaml/yaml.go
- plugin/plugin.go
- plugin/plugin_test.go
- plugin/testdata/test_plugin/plugin.yaml
- policy/compiler.go
- policy/policy.go
This just goes through the codebase and cleans some stuff up to make sure we're keeping things tidy from PR to PR.
> Add additional documentation

- examples/combine/policy/duplicate.rego
- examples/combine/team.yaml
- examples/combine/user1.yaml
- examples/combine/user2.yaml
> Example for #106 : --combine to find duplicates and non-matching fields

- .circleci/config.yml
> Now building docker image with PRs

- go.mod
- go.sum
updates to OPA dependency (0.17.3)
> updates to OPA dependency (0.17.3)

- examples/yamlcombine/README.md
- examples/yamlcombine/ingresses.yaml
- examples/yamlcombine/policy/policy.rego
- examples/yamlcombine/services.yaml
> Adds example for --combine with kubernetes resources. 

- docs/index.md
> Add violation rule to docs

- acceptance.bats
- examples/terraform/policy/gke_combine.rego
- internal/commands/test.go
- policy/namespace.go
This PR fixes #292 
Now nested namespaces work with conftest and I have created a test case to not losing them again.
> Fix broken --namespace

- go.sum
- internal/commands/test.go
- internal/commands/verify.go
- policy/runtime.go
> Inject Opa Runtime term into test & verify commands

- README.md
Signed-off-by: Gareth Rushgrove <gareth@morethanseven.net>
> The CircleCI badge pointed at the old CI project

- internal/commands/test.go
This PR allows for multiple `--namespaces` to be passed
> Allow testing of multiple namespaces

- parser/json/json.go
- parser/parser.go
- parser/parser_test.go
This PR should be able to resolve #323.
> Use encoding/json for json marshalling

- parser/json/json_test.go
As title. 
Better to have a test even a tiny one
> Add testcase for JSON parser

- acceptance.bats
- docs/exceptions.md
- docs/index.md
- examples/exceptions/deployments.yaml
- examples/exceptions/policy/exception.rego
- examples/exceptions/policy/policy.rego
- internal/commands/output.go
- internal/commands/output_test.go
- internal/commands/test.go
- internal/commands/test_test.go
This PR adds support for rule exceptions, as discussed in #315. 
Very much a draft, and open to rebuilding if the approach is bad! Mainly something to get the proverbial ball rolling.
cc @Blokje5
> Exceptions

- .gitignore
- acceptance.bats
Adds a test for multiple namespace flags.
Signed-off-by: garethahealy <garethahealy@gmail.com>
> Added multiple namespace flags to acceptable tests.

- internal/commands/test.go
Ensure exceptions are consistently applied, not only in the multiple objects within a single yaml case.
Fixes #353
Signed-off-by: Lennard Eijsackers <lennardeijsackers92@gmail.com>
> Fix: Exceptions not applied against single input

- internal/commands/default.go
- internal/runner/verify.go
Resolves https://github.com/open-policy-agent/conftest/issues/355
> Report error on verify command

- internal/commands/test.go
- internal/commands/verify.go
- output/result.go
- output/result_test.go
Resolves https://github.com/open-policy-agent/conftest/issues/300
> Add additional exit codes

- examples/ci/gitlab/kubernetes.yaml
Hi this PR fix a typo in the gitlab-ci example.
cheers
> fixed gitlab-ci example

- .dockerignore
- Dockerfile
> Add git to Dockerfile

- policy/engine.go
> Remove warn prefix when evaluating exceptions

- docs/options.md
Resolves https://github.com/open-policy-agent/conftest/issues/485
> Fix formatting error in options documentation

- parser/docker/docker.go
- parser/docker/docker_test.go
Fixes #477
Signed-off-by: Lennard Eijsackers <lennardeijsackers92@gmail.com>
> Support a build stage indicator in the Docker parser.

- examples/ci/gitlab/kubernetes.yaml
Removed the deprecated image and replacing it by the current used image
> Update the source docker image

- go.sum
- internal/commands/pull.go
- internal/commands/push.go
- scripts/push-pull-e2e.sh
Resolves #520 (Inspired from the conversation at https://github.com/deislabs/oras/issues/151) and #505
> Suppress warnings from push and pull

- internal/commands/default.go
- internal/commands/fmt.go
- internal/commands/test.go
- internal/commands/verify.go
> Add fmt command

- .github/workflows/pr.yaml
- .golangci.yaml
- Makefile
- acceptance.bats
- downloader/oci_detector.go
- output/json.go
- output/json_test.go
- output/junit_test.go
- output/standard_test.go
- output/table_test.go
- output/tap.go
- output/tap_test.go
- parser/docker/docker_test.go
- parser/ignore/ignore.go
- parser/ini/ini_test.go
- parser/jsonnet/jsonnet.go
- parser/yaml/yaml_test.go
- plugin/plugin.go
- plugin/xdg.go
- plugin/xdg_test.go
- scripts/push-pull-e2e.sh
Adds more linters to the repository and applies the found fixes.
> Add golangci-lint and lint repository

- internal/commands/test.go
- internal/runner/test.go
> Add no-fail flag

- docs/options.md
> Fix example in documentation

- internal/commands/parse.go
Resolves https://github.com/open-policy-agent/conftest/issues/560
> Update parser documentation for parser flag

- .golangci.yaml
- parser/docker/docker_test.go
- parser/parser.go
- plugin/plugin.go
- policy/engine.go
https://github.com/open-policy-agent/conftest/issues/559
> Organize golangci-lint linters

- docs/install.md
Update docs/install.md (from 0.24.0 to 0.25.0)
Signed-off-by: volanja <volaaanja@gmail.com>
> Update docs/install.md (to 0.25.0)

- acceptance.bats
- examples/dotenv/policy/dotenv.rego
- examples/dotenv/policy/dotenv_test.rego
- examples/dotenv/sample.env
- go.mod
- parser/dotenv/dotenv.go
- parser/dotenv/dotenv_test.go
- parser/parser.go
- parser/parser_test.go
* New parser called `dotenv` added
* Added tests for the parser
* Added examples, with rego examples and rego tests
> Add new parser for .env files.

- DEVELOPMENT.md
Update some commands in developper documentation in order to match with Makefile.
> Update Building and Testing documentation

- internal/commands/default.go
> Fix bug to allow for multiple plugins

- internal/commands/fmt.go
This adds a `--fail` flag to the `fmt` command. The flag name was chosen as this is the same flag that OPA uses, e.g.
```
opa fmt file.rego --fail
```
> Add check flag to fmt command

- docs/index.md
- go.mod
- go.sum
Update documentation and dependencies in preparation for the v0.30.0 release.
> Prepare v0.30.0 release

- .goreleaser.yml
Signed-off-by: Priya Seth <sethp@us.ibm.com>
> Adding ppc64le support

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
Relates to https://github.com/open-policy-agent/conftest/pull/678
> Update Go version in pipelines to 1.17.7

- docs/install.md
install the latest available release instead of fixed version
> Update installation documentation

- internal/commands/push.go
- Do not restrict media types during copy
- Create and set the image config
---
Fixes #716
> Fix 404 error when using the push command

- docs/install.md
> docs: Add instructions for installing from source

- .goreleaser.yml
- Ignore misc commits
- Ignore typo commits
- Group features, bug fixes, key dependency changes, and other changes
---
Following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) style.
> misc: Improve generated changelog

- acceptance.bats
- docs/options.md
- internal/commands/default.go
- internal/commands/test.go
Fixes #786 and provides another pattern to fix #769 and fix #558
> feat: Add --config-file, -c; allow users to set the config file

- Dockerfile
- Makefile
> feat: support multi-arch docker build (linux/arm64 and linux/amd64)

- docs/index.md
No more broken emoji's in the notes!
Fixes: #815
> Fix: Fixes a broken emoji in the NOTES section in the Docs

- acceptance.bats
- docs/index.md
- examples/textproto/fail.textproto
- examples/textproto/pass.textproto
- examples/textproto/policy/over_9000.rego
- examples/textproto/protos/test.proto
- go.mod
- go.sum
- internal/commands/test.go
- internal/commands/verify.go
- parser/parser.go
- parser/parser_test.go
- parser/textproto/textproto.go
- parser/textproto/textproto_test.go
Support parsing and testing the textual representation of Protocol Buffers (textproto).
> Add textproto support

- .github/dependabot.yml
> ci: Have Dependabot auto-update upstream parser libraries

- builtins/parse_config.go
The type does not need to be derived from a parameter to the generic function.
> misc: Clean up generics usage in parse_config

- go.mod
- go.sum
Bump [github.com/docker/docker](https://github.com/docker/docker) from v25.0.3 to v25.0.5
> build(deps): bump github.com/docker/docker from v25.0.3 to v25.0.5

- README.md
Update the quick example referenced in README.md to make it v1 friendly 👍
> docs: Update README.md to make it compatible with v1 syntax

- docs/index.md
some examples were missed during upgrade to v1 syntax.
This PR updates syntax in tests section (https://www.conftest.dev/#using-deny_-as-a-prefix-to-simplify-testing) and cherry-picks non working tests from examples folder.
> docs: update examples to v1 syntax

- plugin/xdg.go
The current check fails to build on Windows due to not having the expected syscall type.
https://github.com/open-policy-agent/conftest/actions/runs/18298766468/job/52102466417
> fix: Fix XDG writable check on Windows
